// Objective-C++ Metal GPU dispatch implementation for DynEarthSol.
//
// Apple Silicon's unified memory architecture means CPU and GPU share the
// same physical DRAM.  Metal buffers created with MTLResourceStorageModeShared
// wrap existing C++ heap pointers at zero-copy cost via newBufferWithBytesNoCopy.
//
// Double-precision arithmetic in Metal shaders requires:
//   MTLGPUFamilyApple8 (M2 / A16 Bionic or newer)
//   MTLGPUFamilyMac2   (discrete AMD Radeon on Intel Macs)
// On M1 (MTLGPUFamilyApple7) and older, metal_init() returns false and every
// dispatch function is a safe no-op; callers use CPU / OpenMP automatically.
//
// Metal shaders are compiled from the embedded source string below.
// Metal caches the compiled binary in ~/Library/Caches/, so the compilation
// overhead is paid only once per GPU firmware version.

#import <Metal/Metal.h>
#import <Foundation/Foundation.h>

#include <cstdio>

#include "metal_dispatch.hpp"

// ---------------------------------------------------------------------------
// Embedded Metal shader source.
// metal_kernels_src.h is auto-generated by the Makefile from metal_kernels.metal
// so this definition is always in sync with the reference .metal file.
// The generated header contains the file content as a C raw string literal.
// ---------------------------------------------------------------------------

static const char *k_metal_src =
#include "metal_kernels_src.h"
;


// ---------------------------------------------------------------------------
// Internal state
// ---------------------------------------------------------------------------

static id<MTLDevice>       g_device    = nil;
static id<MTLCommandQueue> g_queue     = nil;
static id<MTLLibrary>      g_library   = nil;
static bool                g_ready     = false;

static NSMutableDictionary<NSString *, id<MTLComputePipelineState>> *g_pipelines;

// ---------------------------------------------------------------------------
// Helper: get (or compile and cache) a compute pipeline by kernel name
// ---------------------------------------------------------------------------
static id<MTLComputePipelineState> get_pipeline(NSString *name)
{
    id<MTLComputePipelineState> pso = g_pipelines[name];
    if (pso) return pso;

    NSError *err = nil;
    id<MTLFunction> fn = [g_library newFunctionWithName:name];
    if (!fn) {
        fprintf(stderr, "[Metal] kernel '%s' not found\n", name.UTF8String);
        return nil;
    }
    pso = [g_device newComputePipelineStateWithFunction:fn error:&err];
    if (!pso) {
        fprintf(stderr, "[Metal] pipeline '%s' failed: %s\n",
                name.UTF8String, err.localizedDescription.UTF8String);
        return nil;
    }
    g_pipelines[name] = pso;
    return pso;
}

// ---------------------------------------------------------------------------
// Helper: create a zero-copy MTLBuffer wrapping an existing CPU pointer.
// On Apple Silicon the physical memory is unified, so this is truly zero-copy.
// The buffer must not outlive the underlying allocation.
// ---------------------------------------------------------------------------
static id<MTLBuffer> wrap_ptr(const void *ptr, size_t bytes)
{
    return [g_device newBufferWithBytesNoCopy:(void *)ptr
                                       length:bytes
                                      options:MTLResourceStorageModeShared
                                  deallocator:nil];
}

// ---------------------------------------------------------------------------
// Helper: encode and dispatch a 1-D compute kernel, then commit and wait.
// ---------------------------------------------------------------------------
static void commit_1d(id<MTLComputePipelineState> pso,
                      NSArray<id<MTLBuffer>> *bufs,
                      int count)
{
    NSUInteger tgSize = pso.maxTotalThreadsPerThreadgroup;
    if (tgSize > 256) tgSize = 256;

    id<MTLCommandBuffer>        cmdbuf = [g_queue commandBuffer];
    id<MTLComputeCommandEncoder> enc   = [cmdbuf computeCommandEncoder];
    [enc setComputePipelineState:pso];
    for (NSUInteger i = 0; i < bufs.count; i++)
        [enc setBuffer:bufs[i] offset:0 atIndex:i];
    [enc dispatchThreads:MTLSizeMake((NSUInteger)count, 1, 1)
       threadsPerThreadgroup:MTLSizeMake(tgSize, 1, 1)];
    [enc endEncoding];
    [cmdbuf commit];
    [cmdbuf waitUntilCompleted];
}


// ===========================================================================
// Public C API
// ===========================================================================

bool metal_init(void)
{
    if (g_ready) return true;

    g_device = MTLCreateSystemDefaultDevice();
    if (!g_device) {
        fprintf(stderr, "[Metal] No Metal-capable GPU found.\n");
        return false;
    }

    // Double-precision arithmetic is available on:
    //   MTLGPUFamilyApple8 and later  (M2 / A16 Bionic, M3, M4 …)
    //   MTLGPUFamilyMac2              (AMD Radeon on Intel Macs)
    bool supports_double =
        [g_device supportsFamily:MTLGPUFamilyApple8] ||
        [g_device supportsFamily:MTLGPUFamilyMac2];

    if (!supports_double) {
        fprintf(stderr,
            "[Metal] GPU '%s' does not support double-precision arithmetic in "
            "compute shaders (requires Apple GPU Family 8 / M2 or later, or "
            "a Mac 2 discrete GPU).  Falling back to CPU / OpenMP.\n",
            g_device.name.UTF8String);
        g_device = nil;
        return false;
    }

    // Compile shaders from embedded source; Metal caches the result on disk.
    NSError *err = nil;
    NSString *src = [NSString stringWithUTF8String:k_metal_src];
    MTLCompileOptions *opts = [MTLCompileOptions new];
    g_library = [g_device newLibraryWithSource:src options:opts error:&err];
    if (!g_library) {
        fprintf(stderr, "[Metal] Shader compilation failed: %s\n",
                err.localizedDescription.UTF8String);
        g_device = nil;
        return false;
    }

    g_queue     = [g_device newCommandQueue];
    g_pipelines = [NSMutableDictionary dictionary];
    g_ready     = true;

    fprintf(stderr, "[Metal] GPU '%s' enabled (double-precision).\n",
            g_device.name.UTF8String);
    return true;
}

void metal_cleanup(void)
{
    g_pipelines = nil;
    g_library   = nil;
    g_queue     = nil;
    g_device    = nil;
    g_ready     = false;
}

bool metal_gpu_available(void)
{
    return g_ready;
}

// ---------------------------------------------------------------------------
// Geometry kernel: compute_volume
// ---------------------------------------------------------------------------
void metal_compute_volume(
    int ndims, int nelem, int nnode,
    const double *coord, const int *conn,
    double *volume)
{
    if (!g_ready) return;
    int npe = ndims + 1;
    NSString *kname = (ndims == 3) ? @"compute_volume_3d" : @"compute_volume_2d";
    id<MTLComputePipelineState> pso = get_pipeline(kname);
    if (!pso) return;

    id<MTLBuffer> b_coord  = wrap_ptr(coord,  sizeof(double) * (size_t)nnode * ndims);
    id<MTLBuffer> b_conn   = wrap_ptr(conn,   sizeof(int)    * (size_t)nelem * npe);
    id<MTLBuffer> b_volume = wrap_ptr(volume, sizeof(double) * (size_t)nelem);

    commit_1d(pso, @[b_coord, b_conn, b_volume], nelem);
}

// ---------------------------------------------------------------------------
// Field kernel: update_strain_rate
// ---------------------------------------------------------------------------
void metal_update_strain_rate(
    int ndims, int nelem, int nnode,
    const double *vel, const int *conn,
    const double *shpdx, const double *shpdy, const double *shpdz,
    double *strain_rate)
{
    if (!g_ready) return;
    int npe  = ndims + 1;
    int nstr = ndims * (ndims + 1) / 2;

    id<MTLBuffer> b_vel  = wrap_ptr(vel,         sizeof(double) * (size_t)nnode * ndims);
    id<MTLBuffer> b_conn = wrap_ptr(conn,         sizeof(int)    * (size_t)nelem * npe);
    id<MTLBuffer> b_dx   = wrap_ptr(shpdx,        sizeof(double) * (size_t)nelem * npe);
    id<MTLBuffer> b_dz   = wrap_ptr(shpdz,        sizeof(double) * (size_t)nelem * npe);
    id<MTLBuffer> b_sr   = wrap_ptr(strain_rate,  sizeof(double) * (size_t)nelem * nstr);

    if (ndims == 3) {
        id<MTLComputePipelineState> pso = get_pipeline(@"update_strain_rate_3d");
        if (!pso) return;
        id<MTLBuffer> b_dy = wrap_ptr(shpdy, sizeof(double) * (size_t)nelem * npe);
        commit_1d(pso, @[b_vel, b_conn, b_dx, b_dy, b_dz, b_sr], nelem);
    } else {
        id<MTLComputePipelineState> pso = get_pipeline(@"update_strain_rate_2d");
        if (!pso) return;
        commit_1d(pso, @[b_vel, b_conn, b_dx, b_dz, b_sr], nelem);
    }
}

// ---------------------------------------------------------------------------
// Field kernel: update_velocity
// ---------------------------------------------------------------------------
void metal_update_velocity(
    int ndims, int nnode,
    double *vel, const double *force, const double *mass,
    double dt)
{
    if (!g_ready) return;
    NSString *kname = (ndims == 3) ? @"update_velocity_3d" : @"update_velocity_2d";
    id<MTLComputePipelineState> pso = get_pipeline(kname);
    if (!pso) return;

    size_t vec_bytes  = sizeof(double) * (size_t)nnode * ndims;
    size_t mass_bytes = sizeof(double) * (size_t)nnode;

    id<MTLBuffer> b_vel   = wrap_ptr(vel,   vec_bytes);
    id<MTLBuffer> b_force = wrap_ptr(force, vec_bytes);
    id<MTLBuffer> b_mass  = wrap_ptr(mass,  mass_bytes);
    // dt is a small scalar; copy it into a shared buffer
    id<MTLBuffer> b_dt    = [g_device newBufferWithBytes:&dt
                                                  length:sizeof(double)
                                                 options:MTLResourceStorageModeShared];
    commit_1d(pso, @[b_vel, b_force, b_mass, b_dt], nnode);
}

// ---------------------------------------------------------------------------
// Field kernel: update_coordinate
// ---------------------------------------------------------------------------
void metal_update_coordinate(
    int ndims, int nnode,
    double *coord, const double *vel,
    double dt)
{
    if (!g_ready) return;
    NSString *kname = (ndims == 3) ? @"update_coordinate_3d" : @"update_coordinate_2d";
    id<MTLComputePipelineState> pso = get_pipeline(kname);
    if (!pso) return;

    size_t bytes = sizeof(double) * (size_t)nnode * ndims;

    id<MTLBuffer> b_coord = wrap_ptr(coord, bytes);
    id<MTLBuffer> b_vel   = wrap_ptr(vel,   bytes);
    id<MTLBuffer> b_dt    = [g_device newBufferWithBytes:&dt
                                                  length:sizeof(double)
                                                 options:MTLResourceStorageModeShared];
    commit_1d(pso, @[b_coord, b_vel, b_dt], nnode);
}
