#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>
#include <utility>
#include <vector>

#include "runtime_info.hpp"

#ifdef ACC
#include <openacc.h>
#endif
#ifdef _OPENMP
#include <omp.h>
#endif
#ifndef WIN32
#include <pwd.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <unistd.h>
#endif
#ifdef __APPLE__
#include <cstdint>
#include <mach-o/dyld.h>
#include <mach/mach.h>
#include <sys/sysctl.h>
#include <sys/types.h>
#endif
#ifdef __linux__
#include <dirent.h>
#include <set>
#include <sys/utsname.h>
#include <utility>
#endif

#include <boost/version.hpp>
#include <nanoflann.hpp>
#ifdef HDF5
#include <H5public.h>
#endif
#ifdef USEMMG
#include <mmg/common/mmgversion.h>
#endif
#include "binaryio.hpp"

namespace {

// Generated by make: the DES_* identity macros, plus (under snapshot_diff=1)
// DES_HAS_CODE_DIFF and the fenced snapshot_code_diff[] array -- included
// inside the anonymous namespace so the array is not a global.
#include "build_revision.hpp"

// Build-identity sentinel, readable from the binary without running it:
//   strings <exe> | grep '^build\.snapshot\.'
// One copy per topic on this toolchain; a compiler that also emitted the literal into
// .debug_* would print the block twice, identically.
// Curated: versions and build options -- no paths, no environment.
#define DES_STR2(x) #x
#define DES_STR(x) DES_STR2(x)
// One topic per line, each repeating the prefix, so one grep prints the
// whole block: strings splits the array at the embedded newlines.
__attribute__((used)) const char snapshot_sentinel[] =
    // origin = the repo's origin remote, credentials stripped by the make rule.
    // state_utc = when source/config state last CHANGED, not build time; the closest
    // thing to that is exe_mtime_utc, the executable file's mtime, added by its readers.
    "build.snapshot.code       : rev=" DES_REVISION " branch=" DES_BRANCH DES_DIRTY
    " origin=" DES_ORIGIN " state_utc=" DES_STATE_UTC
    // Only the make knobs that are on or carry a value. ndims comes from
    // THREED, keeping build_revision.hpp dimension-neutral.
    "\nbuild.snapshot.options    :"
#ifdef THREED
    " ndims=3 "
#else
    " ndims=2 "
#endif
    DES_MAKE_OPTS
#ifdef ACC
    " gpu_cc=cc" DES_GPU_CC
#endif
    // Fixed at compile time (output.cxx): HDF5Output writes .vtkhdf, else
    // BinaryOutput writes DES's own format. layout = BINARY_FILE_REVISION.
    "\nbuild.snapshot.output     :"
#ifdef HDF5
    " container=vtkhdf"
#else
    " container=des-binary"
#endif
    " layout=" DES_STR(BINARY_FILE_REVISION)
    // In-tree submodules in this build. Checkouts are pinned by the
    // superproject rev; versions repeat here for direct reading.
    "\nbuild.snapshot.submodules :"
#ifdef ACC
    // knn_bvh.hpp has no version macro; make captures the submodule rev.
    " knn-bvh=" DES_KNNBVH_REV
#endif
    // Header-only CPU-side KDTree, in every build. Hex 0xMmP: 0x190 = 1.9.0.
    // version@rev: the upstream release plus the revision this build pinned --
    // a patched submodule reports the same version as an unpatched one.
    " nanoflann=" DES_STR(NANOFLANN_VERSION) "@" DES_NANOFLANN_REV
#ifdef USEMMG
    // usemmg=1 builds the remesher from the in-tree submodule.
    " mmg=" MMG_VERSION_RELEASE DES_MMG_REV "(" DES_SRC_MMG ")"
#endif
    // Ordered by how likely a version difference explains a behavior
    // difference: output container, parallelism, stdlib, options.
    "\nbuild.snapshot.libs       :"
#ifdef HDF5
    " hdf5=" H5_VERSION "(" DES_SRC_HDF5 ")"
#endif
#ifdef _OPENMP
    " openmp=" DES_STR(_OPENMP) "(" DES_SRC_OPENMP ")"
#else
    " openmp=off"
#endif
#if defined(_LIBCPP_VERSION)
    " libcxx=" DES_STR(_LIBCPP_VERSION) "(toolchain)"
#elif defined(__GLIBCXX__)
    " libstdcxx=" DES_STR(__GLIBCXX__) "(toolchain)"
#endif
    " boost=" BOOST_LIB_VERSION "(" DES_SRC_BOOST ")"
    // The toolchain and platform, ahead of the flags they were handed.
    "\nbuild.snapshot.toolchain  :"
    // nvc++'s __VERSION__ names its g++ compatibility mode, so check it first, and
    // clang before __GNUC__ since it defines both. Only g++ leaves its own name out
    // of __VERSION__ ("8.5.0 20210514 (Red Hat 8.5.0-28)"), so only g++ is prefixed.
#if defined(__NVCOMPILER)
    " compiler=nvc++-" DES_STR(__NVCOMPILER_MAJOR__) "." DES_STR(__NVCOMPILER_MINOR__)
#elif defined(__clang__)
    " compiler=" __VERSION__
#elif defined(__GNUC__)
    " compiler=g++ " __VERSION__
#else
    " compiler=" __VERSION__
#endif
    " target="
#if defined(__aarch64__) || defined(__arm64__)
    "arm64"
#elif defined(__x86_64__)
    "x86_64"
#else
    "unknown"
#endif
#if defined(__APPLE__)
    "-darwin"
#elif defined(__linux__)
    "-linux"
#else
    "-unknown"
#endif
    // Flags by stage: compile, defines and warnings reach every .o; link reaches the
    // executable alone -- the link rule passes LDFLAGS and never CXXFLAGS.
    "\nbuild.snapshot.compile    : " DES_CXXFLAGS
    "\nbuild.snapshot.defines    :"
#ifdef THREED
    " -DTHREED"
#endif
    " " DES_DEFINES
    "\nbuild.snapshot.warnings   : " DES_WARNFLAGS
    "\nbuild.snapshot.link       : " DES_LDFLAGS
    // os = the build host's OS (the de facto floor on Linux). builder= is
    // deliberately identifying.
    "\nbuild.snapshot.host       :"
    " os=" DES_BUILD_OS
    " builder=" DES_BUILDER
    ;
#undef DES_STR
#undef DES_STR2


#ifdef ACC
acc_device_t parse_openacc_device_env(const char* env)
{
    if (!env) return acc_device_default;
    std::string s(env);
    std::transform(s.begin(), s.end(), s.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    if (s == "nvidia" || s == "gpu") return acc_device_nvidia;
    if (s == "host" || s == "cpu") return acc_device_host;
    if (s == "none") return acc_device_none;
    if (s == "default") return acc_device_default;
    if (s == "not_host") return acc_device_not_host;
    return acc_device_default;
}

bool env_forces_device(const char* env, acc_device_t& device)
{
    if (!env) return false;
    device = parse_openacc_device_env(env);
    return (device != acc_device_default);
}
#endif

std::string int_or_unknown(int v)
{
    return (v >= 0) ? std::to_string(v) : std::string("unknown");
}

// %.1f for the manifest and the screen; the frame writes the same doubles at full
// precision, so the two artifacts round differently by design.
std::string gib_or_unknown(double gib)
{
    if (gib <= 0) return "unknown";
    char buf[32];
    std::snprintf(buf, sizeof(buf), "%.1f", gib);
    return buf;
}

const char* env_or_unset(const char* name)
{
    const char* v = std::getenv(name);
    return v ? v : "(unset)";
}

// The .manifest uses the input files' own layout: "[section]" then "key = value".
// A value may contain spaces (cpu_model, compiler) but never a newline.
typedef std::pair<std::string, std::string> Field;
typedef std::vector<Field> Fields;

void add(Fields& fs, const std::string& key, const std::string& value)
{
    fs.push_back(Field(key, value));
}

// Two contracts, deliberately: a frame carries a FIXED attribute set, so an unknown
// value there is a sentinel ("unknown", -1, 0) a consumer must reject; the .manifest
// lists only what was probed, so an unknown optional field is simply absent.
void add_section(Manifest& m, const std::string& name, const Fields& fs)
{
    if (fs.empty()) return;      // same rule as write_section: unprobed = absent
    ManifestSection sec;
    sec.name = name;
    sec.fields = fs;
    m.push_back(sec);
}

void write_section(std::FILE* f, const std::string& section, const Fields& fs)
{
    if (fs.empty()) return;
    std::fprintf(f, "[%s]\n", section.c_str());
    for (std::size_t i = 0; i < fs.size(); ++i)
        std::fprintf(f, "%s = %s\n", fs[i].first.c_str(), fs[i].second.c_str());
    std::fprintf(f, "\n");
}

// A key starts with a letter or underscore; a compiler flag starts with '-'. That
// one difference tells a "key=value ..." payload from a bare flag list, so the four
// flag topics need no hard-coded list.
bool is_key_char(char c, bool first)
{
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'
        || (!first && ((c >= '0' && c <= '9') || c == '.' || c == '-'));
}

// Offset of the '=' closing a key that starts at i, or npos if none starts there.
std::size_t key_end_at(const std::string& s, std::size_t i)
{
    if (i >= s.size() || !is_key_char(s[i], true)) return std::string::npos;
    std::size_t j = i + 1;
    while (j < s.size() && is_key_char(s[j], false)) ++j;
    return (j < s.size() && s[j] == '=') ? j : std::string::npos;
}

// Splits a build.snapshot payload into pairs, cutting at the space that begins the
// NEXT key, not at every space: a value may contain spaces ("compiler=Apple LLVM
// 21.0.0 (clang-...) target=arm64-darwin" is two pairs). Empty for a bare flag list.
Fields parse_block_payload(const std::string& payload)
{
    Fields fs;
    std::size_t i = 0;
    while (i < payload.size()) {
        const std::size_t eq = key_end_at(payload, i);
        if (eq == std::string::npos) break;
        std::size_t end = eq + 1;
        while (end < payload.size()) {
            if (payload[end] == ' ' && key_end_at(payload, end + 1) != std::string::npos)
                break;
            ++end;
        }
        add(fs, payload.substr(i, eq - i), payload.substr(eq + 1, end - eq - 1));
        i = (end < payload.size()) ? end + 1 : end;
    }
    return fs;
}


#ifdef __APPLE__
// Returns -1 (or an empty string) when the key does not exist on this hardware,
// e.g. the hw.perflevel* keys are absent on non-hybrid (Intel) Macs.
int sysctl_int32(const char* name)
{
    int32_t value = 0;
    std::size_t len = sizeof(value);
    if (sysctlbyname(name, &value, &len, NULL, 0) != 0 || len != sizeof(value))
        return -1;
    return value;
}

uint64_t sysctl_uint64(const char* name)
{
    uint64_t value = 0;
    std::size_t len = sizeof(value);
    if (sysctlbyname(name, &value, &len, NULL, 0) != 0 || len != sizeof(value))
        return 0;
    return value;
}

std::string sysctl_string(const char* name)
{
    std::size_t len = 0;
    if (sysctlbyname(name, NULL, &len, NULL, 0) != 0 || len == 0)
        return std::string();
    std::string value(len, '\0');
    if (sysctlbyname(name, &value[0], &len, NULL, 0) != 0)
        return std::string();
    // len counts the trailing NUL, which does not belong in a std::string.
    value.resize(len > 0 ? len - 1 : 0);
    return value;
}
#endif // __APPLE__

#ifdef __linux__
std::string trim(const std::string& s)
{
    std::size_t b = 0, e = s.size();
    while (b < e && std::isspace(static_cast<unsigned char>(s[b]))) ++b;
    while (e > b && std::isspace(static_cast<unsigned char>(s[e-1]))) --e;
    return s.substr(b, e - b);
}

// First line of a small procfs/sysfs file, empty when unreadable.
std::string read_first_line(const char* path)
{
    std::ifstream f(path);
    if (!f) return std::string();

    std::string line;
    if (!std::getline(f, line)) return std::string();
    // /proc/device-tree properties are NUL-terminated and getline keeps the terminator.
    const std::size_t nul = line.find('\0');
    if (nul != std::string::npos) line.erase(nul);
    return trim(line);
}

// One pass over /proc/cpuinfo: model name, the distinct (physical id, core id)
// pairs -- the physical core count -- and the ARM implementer/part ids. ARM kernels
// emit none of the first three, so only the ids come back filled.
void read_proc_cpuinfo(std::string& model, int& physical_cores,
                       std::string& arm_implementer, std::string& arm_part)
{
    std::ifstream cpuinfo("/proc/cpuinfo");
    if (!cpuinfo) return;

    std::set<std::pair<int, int> > cores;
    int pkg = -1, core = -1;
    std::string line;
    while (std::getline(cpuinfo, line)) {
        const std::size_t colon = line.find(':');
        if (colon == std::string::npos) {
            // Blank line: end of one processor block.
            if (pkg >= 0 && core >= 0) cores.insert(std::make_pair(pkg, core));
            pkg = core = -1;
            continue;
        }
        const std::string key = trim(line.substr(0, colon));
        const std::string value = trim(line.substr(colon + 1));
        if (key == "model name") {
            if (model.empty()) model = value;
        }
        else if (key == "physical id") pkg = std::atoi(value.c_str());
        else if (key == "core id") core = std::atoi(value.c_str());
        else if (key == "CPU implementer") {
            if (arm_implementer.empty()) arm_implementer = value;
        }
        else if (key == "CPU part") {
            if (arm_part.empty()) arm_part = value;
        }
    }
    if (pkg >= 0 && core >= 0) cores.insert(std::make_pair(pkg, core));

    if (!cores.empty()) physical_cores = static_cast<int>(cores.size());
}

// Physical cores from sysfs: distinct (package, core) pairs. The only one of the two
// that works on ARM. cpu* is enumerated, not indexed -- it is sparse once CPUs are
// offlined; an unreadable core_id skips its CPU rather than counting as core 0.
int read_sysfs_physical_cores()
{
    DIR* dir = opendir("/sys/devices/system/cpu");
    if (!dir) return -1;

    const std::string root = "/sys/devices/system/cpu/";
    std::set<std::pair<int, int> > cores;
    while (const struct dirent* ent = readdir(dir)) {
        const std::string name = ent->d_name;
        if (name.compare(0, 3, "cpu") != 0 || name.size() == 3) continue;
        if (name.find_first_not_of("0123456789", 3) != std::string::npos) continue;

        const std::string topo = root + name + "/topology/";
        const std::string core = read_first_line((topo + "core_id").c_str());
        if (core.empty()) continue;
        const std::string pkg =
            read_first_line((topo + "physical_package_id").c_str());
        cores.insert(std::make_pair(pkg.empty() ? 0 : std::atoi(pkg.c_str()),
                                    std::atoi(core.c_str())));
    }
    closedir(dir);

    return cores.empty() ? -1 : static_cast<int>(cores.size());
}

// Machine identity from DMI, for when the CPU itself is anonymous. Names the host
// rather than the chip, which is still what a wall-clock comparison needs.
std::string read_dmi_model()
{
    const std::string vendor =
        read_first_line("/sys/devices/virtual/dmi/id/sys_vendor");
    const std::string product =
        read_first_line("/sys/devices/virtual/dmi/id/product_name");
    if (vendor.empty()) return product;
    if (product.empty()) return vendor;
    return vendor + " " + product;
}

// One "Key:  N kB" row of /proc/meminfo, in GiB; 0 when absent or unreadable.
double read_proc_meminfo_gib(const char* key)
{
    std::ifstream meminfo("/proc/meminfo");
    if (!meminfo) return 0;

    const std::string prefix = std::string(key) + ":";
    std::string line;
    while (std::getline(meminfo, line)) {
        if (line.compare(0, prefix.size(), prefix) != 0) continue;
        const double kb = std::atof(trim(line.substr(prefix.size())).c_str());
        return kb / (1024.0 * 1024.0);
    }
    return 0;
}

// This process's resident set from /proc/self/status, the runtime counterpart
// of /usr/bin/time's maximum-RSS report.
double read_proc_self_rss_gib()
{
    std::ifstream status("/proc/self/status");
    if (!status) return 0;

    std::string line;
    while (std::getline(status, line)) {
        if (line.compare(0, 6, "VmRSS:") != 0) continue;
        const double kb = std::atof(trim(line.substr(6)).c_str());
        return kb / (1024.0 * 1024.0);
    }
    return 0;
}

// "ID-VERSION_ID" from /etc/os-release (e.g. "ubuntu-22.04"); empty when unreadable.
std::string read_os_release()
{
    std::ifstream f("/etc/os-release");
    if (!f) return std::string();

    std::string id, version, line;
    while (std::getline(f, line)) {
        // Values may be quoted; both fields are single-word by spec.
        std::string* out = NULL;
        if (line.compare(0, 3, "ID=") == 0) { out = &id; line = line.substr(3); }
        else if (line.compare(0, 11, "VERSION_ID=") == 0) { out = &version; line = line.substr(11); }
        if (!out) continue;
        line.erase(std::remove(line.begin(), line.end(), '"'), line.end());
        *out = trim(line);
    }
    if (id.empty()) return std::string();
    return version.empty() ? id : id + "-" + version;
}
#endif // __linux__

std::string read_hostname()
{
#ifndef WIN32
    char buf[256];
    if (gethostname(buf, sizeof(buf)) == 0) {
        buf[sizeof(buf)-1] = '\0';
        return std::string(buf);
    }
#endif
    return "unknown";
}

// %FT%TZ in UTC; "unknown" on failure -- strftime leaves the buffer indeterminate.
std::string utc_stamp(std::time_t t)
{
    char stamp[32];
    if (const std::tm* utc = std::gmtime(&t))
        if (std::strftime(stamp, sizeof(stamp), "%Y-%m-%dT%H:%M:%SZ", utc) > 0)
            return stamp;
    return "unknown";
}

// Link time: the executable's own mtime. The embedded block cannot carry it --
// writing a timestamp into the binary would change the binary.
std::string exe_mtime_utc()
{
    char path[4096];   // Linux PATH_MAX; an over-long path degrades to "unknown"
#if defined(__APPLE__)
    uint32_t size = sizeof(path);
    if (_NSGetExecutablePath(path, &size) != 0) return "unknown";
#elif defined(__linux__)
    const ssize_t n = readlink("/proc/self/exe", path, sizeof(path) - 1);
    if (n <= 0) return "unknown";
    path[n] = '\0';
#else
    return "unknown";
#endif
#ifndef WIN32
    struct stat st;
    if (stat(path, &st) != 0) return "unknown";
    return utc_stamp(st.st_mtime);
#endif
}

// The run host's OS, same labeling as the build-side DES_BUILD_OS.
std::string runtime_os()
{
#if defined(__APPLE__)
    const std::string version = sysctl_string("kern.osproductversion");
    return version.empty() ? "macos" : "macos-" + version;
#elif defined(__linux__)
    const std::string os = read_os_release();
    return os.empty() ? "linux" : os;
#else
    return "unknown";
#endif
}

// user@host, the run-side counterpart of the build's builder=.
std::string runner_id()
{
    std::string user;
#ifndef WIN32
    if (const struct passwd* pw = getpwuid(geteuid()))
        if (pw->pw_name) user = pw->pw_name;
#endif
    if (user.empty()) {
        const char* env_user = std::getenv("USER");
        user = env_user ? env_user : "unknown";
    }
    return user + "@" + read_hostname();
}


#ifdef _OPENMP
// omp_get_max_threads() is only an upper bound: with OMP_DYNAMIC on, the runtime
// may hand out fewer. Open one throwaway region to see the real team size.
int measure_omp_team_size()
{
    int team = 0;
    #pragma omp parallel default(none) shared(team)
    {
        #pragma omp single
        team = omp_get_num_threads();
    }
    return team;
}
#endif

} // namespace

int omp_team_size_now()
{
#ifdef _OPENMP
    return measure_omp_team_size();
#else
    return -1;
#endif
}

std::string utc_now()
{
    return utc_stamp(std::time(NULL));
}

// What other processes left, not a host property: free+speculative+inactive on macOS
// (free_count already counts the speculative pages vm_stat prints apart), MemAvailable
// on Linux. Not comparable across the two -- macOS counts dirty pages Linux withholds.
double host_mem_avail_gib_now()
{
#if defined(__APPLE__)
    // mach_host_self() hands out a send right we own, unlike mach_task_self().
    const mach_port_t self = mach_host_self();
    vm_size_t page = 0;
    vm_statistics64_data_t vm;
    mach_msg_type_number_t count = HOST_VM_INFO64_COUNT;
    const bool ok = host_page_size(self, &page) == KERN_SUCCESS &&
                    host_statistics64(self, HOST_VM_INFO64,
                                      reinterpret_cast<host_info64_t>(&vm),
                                      &count) == KERN_SUCCESS;
    mach_port_deallocate(mach_task_self(), self);
    if (!ok) return 0;
    return (static_cast<double>(vm.free_count) + vm.inactive_count) * page /
           (1024.0 * 1024.0 * 1024.0);
#elif defined(__linux__)
    return read_proc_meminfo_gib("MemAvailable");
#else
    return 0;
#endif
}

double host_mem_rss_gib()
{
#if defined(__APPLE__)
    mach_task_basic_info info;
    mach_msg_type_number_t count = MACH_TASK_BASIC_INFO_COUNT;
    if (task_info(mach_task_self(), MACH_TASK_BASIC_INFO,
                  reinterpret_cast<task_info_t>(&info), &count) != KERN_SUCCESS)
        return 0;
    return static_cast<double>(info.resident_size) / (1024.0 * 1024.0 * 1024.0);
#elif defined(__linux__)
    return read_proc_self_rss_gib();
#else
    return 0;
#endif
}

// Peak resident set: the high-water mark, so a spike between two frames is not
// missed by the instantaneous sample. ru_maxrss is bytes on macOS, kilobytes on Linux.
// Floored at the live resident set: on Linux ru_maxrss is mm->hiwater_rss, which the
// kernel refreshes only at its own call sites and which therefore trails VmRSS -- half of
// one host's frames reported a "peak" below the rss in the same record. The floor makes
// this a lower bound, not a high-water mark: it falls with the rss once the live value
// has overtaken a stale ru_maxrss, so the caller keeps the running maximum.
double host_peak_rss_gib()
{
#ifndef WIN32
    struct rusage ru;
    if (getrusage(RUSAGE_SELF, &ru) != 0) return 0;
#if defined(__APPLE__)
    const double peak = static_cast<double>(ru.ru_maxrss) / (1024.0 * 1024.0 * 1024.0);
#else
    const double peak = static_cast<double>(ru.ru_maxrss) / (1024.0 * 1024.0);
#endif
    return std::max(peak, host_mem_rss_gib());
#else
    return 0;
#endif
}

// CPU seconds this process has burned, user + system. Against the frame's
// walltime_sec and omp_threads it gives the parallel efficiency, so a stalling
// region or an oversubscribed host shows up as a falling ratio.
double process_cpu_time_sec()
{
#ifndef WIN32
    struct rusage ru;
    if (getrusage(RUSAGE_SELF, &ru) != 0) return 0;
    return ru.ru_utime.tv_sec + ru.ru_utime.tv_usec * 1e-6
         + ru.ru_stime.tv_sec + ru.ru_stime.tv_usec * 1e-6;
#else
    return 0;
#endif
}

// One-minute load average: contention from everything else on the machine, which
// is what separates "the model slowed down" from "the machine got busy".
double host_load_avg_1m()
{
#ifndef WIN32
    double la[1] = {0};
    if (getloadavg(la, 1) != 1) return 0;
    return la[0];
#else
    return 0;
#endif
}

double device_mem_used_dev_gib(const DeviceInfo& dev)
{
#ifdef ACC
    if (dev.using_gpu && dev.mem_total_gib > 0) {
        const acc_device_t type = acc_get_device_type();
        const size_t free_now =
            acc_get_property(acc_get_device_num(type), type, acc_property_free_memory);
        if (free_now)
            return dev.mem_total_gib -
                   static_cast<double>(free_now) / (1024.0 * 1024.0 * 1024.0);
    }
#else
    (void)dev;
#endif
    return 0;
}

BuildInfo probe_build_info()
{
    BuildInfo b;

    // Identity restated as fields so the frame writer never parses the sentinel text.
    // Build CONFIGURATION is deliberately NOT restated: it reaches a reader through the
    // block's own options/toolchain/defines lines.
    b.rev = DES_REVISION;
    b.branch = DES_BRANCH;
    const std::string dirty(DES_DIRTY);   // " dirty=2f/+13/-12"/" dirty=unknown", "" = clean
    const std::size_t eq = dirty.find('=');
    b.dirty = (eq == std::string::npos) ? "clean" : dirty.substr(eq + 1);
    b.origin = DES_ORIGIN;
    b.state_utc = DES_STATE_UTC;
    b.build_os = DES_BUILD_OS;
    b.builder = DES_BUILDER;
    b.exe_mtime_utc = exe_mtime_utc();

    return b;
}


CpuInfo probe_cpu_info(bool wait_policy_from_des)
{
    CpuInfo cpu;
    cpu.model = "unknown";
    cpu.logical_cores = -1;
    cpu.physical_cores = -1;
    cpu.perf_cores = -1;
    cpu.eff_cores = -1;
    cpu.mem_total_gib = 0;
    cpu.mem_avail_gib = 0;
    cpu.openmp_enabled = false;
    cpu.omp_team_size = -1;
    cpu.omp_max_threads = -1;
    cpu.omp_num_procs = -1;
    cpu.omp_dynamic = false;

    cpu.os = runtime_os();
    cpu.runner = runner_id();
    cpu.mem_avail_gib = host_mem_avail_gib_now();

    const unsigned int hw_threads = std::thread::hardware_concurrency();
    if (hw_threads) cpu.logical_cores = static_cast<int>(hw_threads);

#ifdef __APPLE__
    const std::string brand = sysctl_string("machdep.cpu.brand_string");
    if (!brand.empty()) cpu.model = brand;
    else {
        const std::string hw_model = sysctl_string("hw.model");
        if (!hw_model.empty()) cpu.model = hw_model;
    }
    cpu.physical_cores = sysctl_int32("hw.physicalcpu");
    const int logical = sysctl_int32("hw.logicalcpu");
    if (logical > 0) cpu.logical_cores = logical;
    // Only a two-tier part maps onto perf/eff; a third tier leaves eff unknown rather
    // than silently naming tier 1 the whole efficiency side.
    cpu.perf_cores = sysctl_int32("hw.perflevel0.physicalcpu");
    if (sysctl_int32("hw.nperflevels") == 2)
        cpu.eff_cores = sysctl_int32("hw.perflevel1.physicalcpu");
    const uint64_t memsize = sysctl_uint64("hw.memsize");
    if (memsize) cpu.mem_total_gib = static_cast<double>(memsize) /
                                    (1024.0 * 1024.0 * 1024.0);
#elif defined(__linux__)
    // /proc/cpuinfo first so x86 hosts report what they did before, then sysfs.
    std::string model, arm_implementer, arm_part;
    read_proc_cpuinfo(model, cpu.physical_cores, arm_implementer, arm_part);
    if (cpu.physical_cores < 0) cpu.physical_cores = read_sysfs_physical_cores();

    // Name the host from whichever source answers, chip first then machine: ARM boards
    // publish a device-tree model, servers and cloud instances publish DMI strings.
    if (model.empty()) model = read_first_line("/proc/device-tree/model");
    if (model.empty()) model = read_dmi_model();
    if (model.empty() && !arm_implementer.empty() && !arm_part.empty()) {
        // Last resort on an anonymous ARM core: the raw ids identify it to a human. NOT
        // decoded to a name -- a part-number table would go stale with every new core.
        struct utsname uts;
        const std::string machine = (uname(&uts) == 0) ? uts.machine : "";
        model = machine + (machine.empty() ? "" : " ") +
                "(CPU implementer " + arm_implementer +
                ", part " + arm_part + ")";
    }
    if (!model.empty()) cpu.model = model;
    cpu.mem_total_gib = read_proc_meminfo_gib("MemTotal");
#endif

#ifdef _OPENMP
    cpu.openmp_enabled = true;
    cpu.omp_max_threads = omp_get_max_threads();
    cpu.omp_num_procs = omp_get_num_procs();
    cpu.omp_dynamic = (omp_get_dynamic() != 0);
    cpu.omp_team_size = measure_omp_team_size();
#endif

    // Non-empty, matching what omp_wait_policy_eff acts on: a variable exported empty
    // governs nothing, so calling it "env" would claim a policy beside eff's "default".
    const char* const wp = std::getenv("OMP_WAIT_POLICY");
    const char* const bt = std::getenv("KMP_BLOCKTIME");
    if (wait_policy_from_des)
        cpu.wait_policy_src = "des-default";
    else if ((wp && *wp) || (bt && *bt))
        cpu.wait_policy_src = "env";
    else
        cpu.wait_policy_src = "runtime";

    return cpu;
}

Manifest compose_manifest(const Param& param, const BuildInfo& build,
                          const CpuInfo& cpu, const DeviceInfo& dev)
{
    Manifest m;
    Fields run;
    add(run, "modelname", param.sim.modelname);
    add(run, "restarting", param.sim.is_restarting ? "yes" : "no");
    if (param.sim.is_restarting) {
        add(run, "restart_from_model", param.sim.restarting_from_modelname);
        add(run, "restart_from_frame", std::to_string(param.sim.restarting_from_frame));
    }
    add(run, "start_utc", utc_now());
    add_section(m, "runtime.model", run);

    // The host this run got, run-side counterpart of the block's host line.
    Fields host;
    add(host, "os", cpu.os);
    add(host, "runner", cpu.runner);
    add(host, "cpu_model", cpu.model);
    add(host, "physical_cores", int_or_unknown(cpu.physical_cores));
    add(host, "logical_cores", int_or_unknown(cpu.logical_cores));
    add(host, "perf_cores", int_or_unknown(cpu.perf_cores));
    add(host, "eff_cores", int_or_unknown(cpu.eff_cores));
    add(host, "mem_total_gib", gib_or_unknown(cpu.mem_total_gib));
    // A snapshot of what other processes left, not comparable across runs.
    add(host, "mem_avail_at_start_gib", gib_or_unknown(cpu.mem_avail_gib));
    add_section(m, "runtime.host", host);

    // The device: an openacc=1 binary silently falls back to the host when it finds no
    // NVIDIA device, so the build alone does not say where the arithmetic happened.
    Fields device;
    add(device, "kernel", dev.kernel);
    // Before the using_gpu block: a run that found no device writes this manifest and
    // nothing else, and an empty filter -- "none" -- is why it found none.
    if (dev.acc_build)
        add(device, "visible_devices", dev.visible_devices);
    if (dev.using_gpu) {
        if (!dev.name.empty()) add(device, "name", dev.name);
        add(device, "selected", std::to_string(dev.active_dev) + "/"
                              + std::to_string(dev.num_devices));
        if (!dev.cuda_driver.empty()) add(device, "cuda_driver", dev.cuda_driver);
        add(device, "mem_total_gib", gib_or_unknown(dev.mem_total_gib));
        add(device, "mem_free_at_start_gib", gib_or_unknown(dev.mem_free_gib));
    }
    add_section(m, "runtime.device", device);

    Fields threads;
    add(threads, "openmp", cpu.openmp_enabled ? "enabled" : "disabled");
    if (cpu.openmp_enabled) {
        add(threads, "omp_threads", int_or_unknown(cpu.omp_team_size));
        add(threads, "omp_max_threads", int_or_unknown(cpu.omp_max_threads));
        add(threads, "omp_num_procs", int_or_unknown(cpu.omp_num_procs));
        add(threads, "omp_dynamic", cpu.omp_dynamic ? "on" : "off");
        // Names what was set, not one resolved policy: libomp lets KMP_BLOCKTIME set the
        // spin time whenever it is set and OMP_WAIT_POLICY only the library mode, so
        // either alone asserts the wrong thing when both are. Measured: libgomp and
        // nvomp honour OMP_WAIT_POLICY and ignore KMP_BLOCKTIME entirely, so on those
        // the blocktime term records an intent the runtime did not act on.
        // Always emitted: absent would read as "not probed".
        std::string policy;
        if (const char* wait = std::getenv("OMP_WAIT_POLICY"))
            if (*wait) policy = wait;
        if (const char* bt = std::getenv("KMP_BLOCKTIME"))
            if (*bt) policy += (policy.empty() ? "" : "+") + std::string("blocktime=") + bt;
        add(threads, "omp_wait_policy_eff", policy.empty() ? "default" : policy);
        add(threads, "omp_wait_policy_src", cpu.wait_policy_src);
    }
    add_section(m, "runtime.threads", threads);

    // Only the variables that are set: an unset entry carries no information, and the
    // effective values they steer are all recorded above.
    const char* const env_names[] = {
        "OMP_NUM_THREADS", "OMP_THREAD_LIMIT", "OMP_DYNAMIC", "OMP_PROC_BIND",
        // Listed on every platform: it is set by the time this runs, and on macOS main()
        // is what set it -- so a manifest that omitted it would hide a variable the run
        // had. Which of the two set it follows from the rule main() prints: on macOS,
        // active with no KMP_BLOCKTIME beside it is DES's own default.
        "OMP_PLACES", "OMP_WAIT_POLICY", "KMP_BLOCKTIME",
    };
    // The device-selection variables, measured to move a run between physical cards.
    // Only on an ACC build: elsewhere they steer nothing and read as if they had.
    const char* const acc_env_names[] = {
        "CUDA_VISIBLE_DEVICES", "ACC_DEVICE_TYPE", "ACC_DEVICE_NUM",
        "NVCOMPILER_ACC_DEVICE_TYPE", "NVCOMPILER_ACC_DEVICE_NUM"
    };
    Fields env;
    for (std::size_t i = 0; i < sizeof(env_names) / sizeof(env_names[0]); ++i)
        if (const char* v = std::getenv(env_names[i]))
            add(env, env_names[i], v);
    if (dev.acc_build)
        for (std::size_t i = 0; i < sizeof(acc_env_names) / sizeof(acc_env_names[0]); ++i)
            if (const char* v = std::getenv(acc_env_names[i]))
                add(env, acc_env_names[i], v);
    add_section(m, "runtime.env", env);

    // The embedded build.snapshot block, re-expressed as sections: the binary's
    // literal stays the single source of truth. exe_mtime_utc joins its host line here
    // because the block cannot carry its own link time; the host line closes the
    // block, so appending the pair before parsing files it in the right section.
    const std::string block = std::string(snapshot_sentinel)
                            + " exe_mtime_utc=" + build.exe_mtime_utc;
    std::istringstream blocklines(block);
    std::string line;
    Fields compile, link, other;        // the bare-flag-list topics, by stage
    while (std::getline(blocklines, line)) {
        const std::size_t sep = line.find(" : ");
        if (sep == std::string::npos) {
            // Unreachable today (every topic has an unconditional member), but the
            // payloads are preprocessor-assembled: keep the line rather than lose it.
            add(other, "unparsed", line);
            continue;
        }
        std::string topic = line.substr(0, sep);
        const std::size_t dot = topic.rfind('.');
        if (dot != std::string::npos) topic = topic.substr(dot + 1);
        while (!topic.empty() && topic[topic.size() - 1] == ' ')   // column padding
            topic.erase(topic.size() - 1);

        const std::string payload = line.substr(sep + 3);
        const Fields fields = parse_block_payload(payload);
        if (fields.empty()) {
            // A bare flag list, filed by the stage that saw it: compile flags reach
            // every .o, link flags the executable alone -- the link rule passes LDFLAGS
            // and never CXXFLAGS. defines and warnings are compile-side too.
            if (topic == "link")         add(link, "flags", payload);
            else if (topic == "compile") add(compile, "flags", payload);
            else                         add(compile, topic, payload);
        }
        else
            add_section(m, "build." + topic, fields);
    }
    add_section(m, "build.compile", compile);
    add_section(m, "build.link", link);
    add_section(m, "build.unparsed", other);
    return m;
}

void write_manifest(const Param& param, const Manifest& manifest, bool keep_existing)
{
    const std::string filename(param.sim.modelname + ".manifest");

    // Appended on a restart, so a resume onto another host stays readable; truncated on a
    // fresh run, matching .info, since re-running a model name replaces its frames. A run
    // that is about to fail appends instead: it replaces no frames, so it must not replace
    // the record of the run whose frames are still there.
    const bool append = param.sim.is_restarting || keep_existing;
    std::FILE* f = std::fopen(filename.c_str(), append ? "a" : "w");
    if (f == NULL) {
        // Provenance is diagnostic-only -- it must never abort a run.
        std::cerr << "Warning: cannot open file '" << filename
                  << "' for writing; run provenance not recorded\n";
        return;
    }

    // An appended record needs a visible seam; [runtime.model] restarting= tells the records apart.
    // Guarded on ftell: a restart into a directory with no manifest writes the FIRST record.
    std::fseek(f, 0, SEEK_END);
    if (append && std::ftell(f) > 0)
        std::fprintf(f, keep_existing
                        ? "# ---- a run that could not start follows ----\n\n"
                        : "# ---- restart: another record follows ----\n\n");

    for (std::size_t i = 0; i < manifest.size(); ++i)
        write_section(f, manifest[i].name, manifest[i].fields);

#ifdef DES_HAS_CODE_DIFF
    // The embedded payload, verbatim and fenced, so one sed recipe reads it out of
    // the manifest and out of the binary. Last, because it is the only unbounded
    // part of the record (1 MB cap) and the only part that is not INI.
    std::fprintf(f, "%s\n", snapshot_code_diff);
#else
    // Stated, not left to a missing section: "not built with it" and "built with it and
    // the tree was clean" must not look alike. A comment, so no parser reads it as a key.
    std::fprintf(f, "# build.code-changes: not embedded"
                    " -- this binary was built without snapshot_diff=1\n");
#endif

    // Check the error flag AND fclose: the record is smaller than the stdio buffer, so
    // on a full disk ferror still reads clean while fclose fails and the record is lost.
    const bool write_failed = (std::ferror(f) != 0);
    const bool close_failed = (std::fclose(f) != 0);
    if (write_failed || close_failed)
        std::cerr << "Warning: failed writing to file '" << filename
                  << "'; run provenance may be incomplete\n";
}

// The only place the device is CHOSEN -- never skip or reorder it;
// report_build_and_runtime_info() below only prints. mem_free is sampled here at
// selection time: a snapshot of what other processes left, not a device property.
DeviceInfo init_offload_device()
{
    DeviceInfo dev;
    dev.acc_build = false;
    dev.using_gpu = false;
    dev.kernel = "CPU";
    dev.num_devices = 0;
    dev.active_dev = -1;
    dev.mem_total_gib = 0;
    dev.mem_free_gib = 0;

#ifdef ACC
    dev.acc_build = true;

    // Read here, not at write time: it is what selected the device below, and an empty
    // value hides every one of them -- the case the field most has to distinguish.
    const char* visible = std::getenv("CUDA_VISIBLE_DEVICES");
    dev.visible_devices = !visible ? "all" : (*visible ? visible : "none");

    const int n_nvidia = acc_get_num_devices(acc_device_nvidia);
    dev.num_devices = n_nvidia;

    acc_device_t forced = acc_device_default;
    const bool forced_by_env =
        env_forces_device(std::getenv("ACC_DEVICE_TYPE"), forced) ||
        env_forces_device(std::getenv("NVCOMPILER_ACC_DEVICE_TYPE"), forced);

    if (forced_by_env) {
        acc_set_device_type(forced);
        acc_init(forced);
    }
    else if (n_nvidia > 0) {
        acc_set_device_type(acc_device_nvidia);
        acc_init(acc_device_nvidia);
    }
    else {
        acc_set_device_type(acc_device_host);
        acc_init(acc_device_host);
    }

    const acc_device_t active_type = acc_get_device_type();
    const int active_dev = acc_get_device_num(active_type);
    dev.using_gpu = (active_type == acc_device_nvidia && n_nvidia > 0);
    dev.kernel = dev.using_gpu ? "GPU" : "CPU";
    dev.active_dev = dev.using_gpu ? active_dev : -1;

    const char* name = acc_get_property_string(active_dev, active_type, acc_property_name);
    const char* vendor = acc_get_property_string(active_dev, active_type, acc_property_vendor);
    const char* driver = acc_get_property_string(active_dev, active_type, acc_property_driver);
    if (name) dev.name = name;
    if (vendor) dev.vendor = vendor;
    if (driver) dev.cuda_driver = driver;

    const size_t mem_total = acc_get_property(active_dev, active_type, acc_property_memory);
    if (mem_total)
        dev.mem_total_gib = static_cast<double>(mem_total) / (1024.0 * 1024.0 * 1024.0);
    const size_t mem_free = acc_get_property(active_dev, active_type, acc_property_free_memory);
    if (mem_free)
        dev.mem_free_gib = static_cast<double>(mem_free) / (1024.0 * 1024.0 * 1024.0);
#endif

    return dev;
}

// "[group][topic] key=value, ..." for the section "group.topic".
static void print_section(const ManifestSection& sec)
{
    const std::size_t dot = sec.name.find('.');
    std::cout << '[' << sec.name.substr(0, dot) << ']'
              << '[' << (dot == std::string::npos ? "" : sec.name.substr(dot + 1)) << ']';
    for (std::size_t k = 0; k < sec.fields.size(); ++k)
        std::cout << (k ? ", " : " ") << sec.fields[k].first << '=' << sec.fields[k].second;
    std::cout << '\n';
}

void report_build_and_runtime_info(const Manifest& manifest)
{
    // Build first, then runtime: what the binary is, then what it ran on. The file
    // keeps the manifest's own order.
    const std::string groups[] = { "build.", "runtime." };
    for (std::size_t g = 0; g < 2; ++g) {
        for (std::size_t i = 0; i < manifest.size(); ++i)
            if (manifest[i].name.compare(0, groups[g].size(), groups[g]) == 0)
                print_section(manifest[i]);
        if (g == 0) {
            // The manifest's own closing line, in the same words.
#ifdef DES_HAS_CODE_DIFF
            std::cout << "[build][code-changes] embedded -- see -h for the extraction\n";
#else
            std::cout << "[build][code-changes] not embedded"
                         " -- this binary was built without snapshot_diff=1\n";
#endif
        }
    }
}

void report_mesh_info(const Variables& var, const char* tag)
{
    std::cout << "[Runtime][Mesh] " << tag
              << " nodes=" << var.nnode
              << ", elements=" << var.nelem
              << ", segments=" << var.nseg
              << '\n';
}
