#include <algorithm>
#include <cctype>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>

#include "runtime_info.hpp"

#ifdef ACC
#include <openacc.h>
#endif
#ifdef _OPENMP
#include <omp.h>
#endif
#ifndef WIN32
#include <sys/stat.h>
#include <unistd.h>
#endif
#ifdef __APPLE__
#include <cstdint>
#include <mach-o/dyld.h>
#include <sys/sysctl.h>
#include <sys/types.h>
#endif

#include <boost/version.hpp>
#include <nanoflann.hpp>
#ifdef HDF5
#include <H5public.h>
#endif
#ifdef USEMMG
#include <mmg/common/mmgversion.h>
#endif
#include "binaryio.hpp"

namespace {

// Generated by make: the DES_* identity macros, plus (under snapshot_diff=1)
// DES_HAS_CODE_DIFF and the fenced snapshot_code_diff[] array -- included
// inside the anonymous namespace so the array is not a global.
#include "build_revision.hpp"

// Build-identity sentinel, readable from the binary without running it:
//   strings <exe> | grep '^build\.snapshot\.'
// One copy per topic on this toolchain; a compiler that also emitted the literal into
// .debug_* would print the block twice, identically.
// Curated: versions and build options -- no paths, no environment.
#define DES_STR2(x) #x
#define DES_STR(x) DES_STR2(x)
// One topic per line, each repeating the prefix, so one grep prints the
// whole block: strings splits the array at the embedded newlines.
__attribute__((used)) const char snapshot_sentinel[] =
    // origin = the repo's origin remote, credentials stripped by the make rule.
    // state_utc = when source/config state last CHANGED, not link time; the link
    // time is build_utc, taken from the executable's mtime by the .manifest writer.
    "build.snapshot.code       : rev=" DES_REVISION " branch=" DES_BRANCH DES_DIRTY
    " origin=" DES_ORIGIN " state_utc=" DES_STATE_UTC
    // Only the make knobs that are on or carry a value. ndims comes from
    // THREED, keeping build_revision.hpp dimension-neutral.
    "\nbuild.snapshot.options    :"
#ifdef THREED
    " ndims=3 "
#else
    " ndims=2 "
#endif
    DES_MAKE_OPTS
#ifdef ACC
    " gpu_cc=cc" DES_GPU_CC
#endif
    // Fixed at compile time (output.cxx): HDF5Output writes .vtkhdf, else
    // BinaryOutput writes DES's own format. layout = BINARY_FILE_REVISION.
    "\nbuild.snapshot.output     :"
#ifdef HDF5
    " container=vtkhdf"
#else
    " container=des-binary"
#endif
    " layout=" DES_STR(BINARY_FILE_REVISION)
    // In-tree submodules in this build. Checkouts are pinned by the
    // superproject rev; versions repeat here for direct reading.
    "\nbuild.snapshot.submodules :"
#ifdef ACC
    // knn_bvh.hpp has no version macro; make captures the submodule rev.
    " knn-bvh=" DES_KNNBVH_REV
#endif
    // Header-only CPU-side KDTree, in every build. Hex 0xMmP: 0x190 = 1.9.0.
    // version@rev: the upstream release plus the revision this build pinned --
    // a patched submodule reports the same version as an unpatched one.
    " nanoflann=" DES_STR(NANOFLANN_VERSION) "@" DES_NANOFLANN_REV
#ifdef USEMMG
    // usemmg=1 builds the remesher from the in-tree submodule.
    " mmg=" MMG_VERSION_RELEASE DES_MMG_REV "(" DES_SRC_MMG ")"
#endif
    // Ordered by how likely a version difference explains a behavior
    // difference: output container, parallelism, stdlib, options.
    "\nbuild.snapshot.libs       :"
#ifdef HDF5
    " hdf5=" H5_VERSION "(" DES_SRC_HDF5 ")"
#endif
#ifdef _OPENMP
    " openmp=" DES_STR(_OPENMP) "(" DES_SRC_OPENMP ")"
#else
    " openmp=off"
#endif
#if defined(_LIBCPP_VERSION)
    " libcxx=" DES_STR(_LIBCPP_VERSION) "(toolchain)"
#elif defined(__GLIBCXX__)
    " libstdcxx=" DES_STR(__GLIBCXX__) "(toolchain)"
#endif
    " boost=" BOOST_LIB_VERSION "(" DES_SRC_BOOST ")"
    // The toolchain and platform, ahead of the flags they were handed.
    "\nbuild.snapshot.toolchain  :"
    // nvc++'s __VERSION__ names its g++ compatibility mode, so check it first, and
    // clang before __GNUC__ since it defines both. Only g++ leaves its own name out
    // of __VERSION__ ("8.5.0 20210514 (Red Hat 8.5.0-28)"), so only g++ is prefixed.
#if defined(__NVCOMPILER)
    " compiler=nvc++-" DES_STR(__NVCOMPILER_MAJOR__) "." DES_STR(__NVCOMPILER_MINOR__)
#elif defined(__clang__)
    " compiler=" __VERSION__
#elif defined(__GNUC__)
    " compiler=g++ " __VERSION__
#else
    " compiler=" __VERSION__
#endif
    " target="
#if defined(__aarch64__) || defined(__arm64__)
    "arm64"
#elif defined(__x86_64__)
    "x86_64"
#else
    "unknown"
#endif
#if defined(__APPLE__)
    "-darwin"
#elif defined(__linux__)
    "-linux"
#else
    "-unknown"
#endif
    // Flags by stage: compile, defines and warnings reach every .o; link reaches the
    // executable alone -- the link rule passes LDFLAGS and never CXXFLAGS.
    "\nbuild.snapshot.compile    : " DES_CXXFLAGS
    "\nbuild.snapshot.defines    :"
#ifdef THREED
    " -DTHREED"
#endif
    " " DES_DEFINES
    "\nbuild.snapshot.warnings   : " DES_WARNFLAGS
    "\nbuild.snapshot.link       : " DES_LDFLAGS
    // os = the build host's OS (the de facto floor on Linux). builder= is
    // deliberately identifying.
    "\nbuild.snapshot.host       :"
    " os=" DES_BUILD_OS
    " builder=" DES_BUILDER
    ;
#undef DES_STR
#undef DES_STR2



#ifdef ACC
const char* openacc_device_name(acc_device_t t)
{
    switch (t) {
    case acc_device_nvidia: return "nvidia";
    case acc_device_host: return "host";
    case acc_device_none: return "none";
    case acc_device_default: return "default";
    case acc_device_not_host: return "not_host";
    default: return "unknown";
    }
}

acc_device_t parse_openacc_device_env(const char* env)
{
    if (!env) return acc_device_default;
    std::string s(env);
    std::transform(s.begin(), s.end(), s.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    if (s == "nvidia" || s == "gpu") return acc_device_nvidia;
    if (s == "host" || s == "cpu") return acc_device_host;
    if (s == "none") return acc_device_none;
    if (s == "default") return acc_device_default;
    if (s == "not_host") return acc_device_not_host;
    return acc_device_default;
}

bool env_forces_device(const char* env, acc_device_t& device)
{
    if (!env) return false;
    device = parse_openacc_device_env(env);
    return (device != acc_device_default);
}

bool using_offload_device()
{
    return (acc_get_device_type() == acc_device_nvidia &&
            acc_get_num_devices(acc_device_nvidia) > 0);
}

const char* env_or_unset(const char* name)
{
    const char* v = std::getenv(name);
    return v ? v : "(unset)";
}
#endif

std::string read_cpu_model()
{
#ifdef __APPLE__
    // No /proc on macOS; the brand string lives in sysctl.
    std::size_t len = 0;
    if (sysctlbyname("machdep.cpu.brand_string", NULL, &len, NULL, 0) != 0 || len == 0)
        return "unknown";
    std::string model(len, '\0');
    if (sysctlbyname("machdep.cpu.brand_string", &model[0], &len, NULL, 0) != 0)
        return "unknown";
    // len counts the trailing NUL, which does not belong in a std::string.
    model.resize(len > 0 ? len - 1 : 0);
    return model.empty() ? "unknown" : model;
#else
    std::ifstream cpuinfo("/proc/cpuinfo");
    if (!cpuinfo) return "unknown";

    std::string line;
    while (std::getline(cpuinfo, line)) {
        const std::size_t pos = line.find("model name");
        if (pos == std::string::npos) continue;
        const std::size_t colon = line.find(':', pos);
        if (colon == std::string::npos) continue;
        std::string model = line.substr(colon + 1);
        while (!model.empty() && std::isspace(static_cast<unsigned char>(model.front())))
            model.erase(model.begin());
        if (!model.empty()) return model;
    }
    return "unknown";
#endif
}

// %FT%TZ in UTC; "unknown" on failure -- strftime leaves the buffer indeterminate.
std::string utc_stamp(std::time_t t)
{
    char stamp[32];
    if (const std::tm* utc = std::gmtime(&t))
        if (std::strftime(stamp, sizeof(stamp), "%Y-%m-%dT%H:%M:%SZ", utc) > 0)
            return stamp;
    return "unknown";
}

// Link time: the executable's own mtime. The embedded block cannot carry it --
// writing a timestamp into the binary would change the binary.
std::string exe_mtime_utc()
{
    char path[4096];   // Linux PATH_MAX; an over-long path degrades to "unknown"
#if defined(__APPLE__)
    uint32_t size = sizeof(path);
    if (_NSGetExecutablePath(path, &size) != 0) return "unknown";
#elif defined(__linux__)
    const ssize_t n = readlink("/proc/self/exe", path, sizeof(path) - 1);
    if (n <= 0) return "unknown";
    path[n] = '\0';
#else
    return "unknown";
#endif
#ifndef WIN32
    struct stat st;
    if (stat(path, &st) != 0) return "unknown";
    return utc_stamp(st.st_mtime);
#endif
}

} // namespace

void report_host_runtime_status()
{
    const std::string cpu_model = read_cpu_model();
    const unsigned int hw_threads = std::thread::hardware_concurrency();
    std::cout << "[Runtime][Host] name=" << cpu_model
              << ", hw_threads="
              << (hw_threads ? std::to_string(hw_threads) : "unknown");
#ifdef _OPENMP
    std::cout << ", openmp_max_threads=" << omp_get_max_threads()
              << ", openmp_num_procs=" << omp_get_num_procs()
              << ", openmp_dynamic=" << (omp_get_dynamic() ? "on" : "off");
#else
    std::cout << ", openmp=disabled";
#endif
    std::cout << '\n';
}

void init_offload_device()
{
#ifdef ACC
    acc_device_t forced = acc_device_default;
    const bool forced_by_env =
        env_forces_device(std::getenv("ACC_DEVICE_TYPE"), forced) ||
        env_forces_device(std::getenv("NVCOMPILER_ACC_DEVICE_TYPE"), forced);

    if (forced_by_env) {
        acc_set_device_type(forced);
        acc_init(forced);
    }
    else if (acc_get_num_devices(acc_device_nvidia) > 0) {
        acc_set_device_type(acc_device_nvidia);
        acc_init(acc_device_nvidia);
    }
    else {
        acc_set_device_type(acc_device_host);
        acc_init(acc_device_host);
    }
#endif
}

void report_device_runtime_status()
{
#ifndef ACC
    std::cout << "[Runtime][Device] build=non-ACC, kernel=CPU\n";
#else
    const acc_device_t active_type = acc_get_device_type();
    const int active_dev = acc_get_device_num(active_type);
    const bool using_device = using_offload_device();

    // The selection picture: the steering environment (these two can force the
    // device type), what was visible, and what was chosen.
    std::cout << "[Runtime][Device] build=ACC"
              << ", env.ACC_DEVICE_TYPE=" << env_or_unset("ACC_DEVICE_TYPE")
              << ", env.NVCOMPILER_ACC_DEVICE_TYPE="
              << env_or_unset("NVCOMPILER_ACC_DEVICE_TYPE");
    // When set it renumbers devices from 0, so num_nvidia and active_dev below
    // count within the remapped set, not the physical machine.
    const char* visible = std::getenv("CUDA_VISIBLE_DEVICES");
    if (visible)
        std::cout << ", env.CUDA_VISIBLE_DEVICES=" << visible;
    std::cout << ", num_nvidia=" << acc_get_num_devices(acc_device_nvidia)
              << ", num_host=" << acc_get_num_devices(acc_device_host)
              << ", active_type=" << openacc_device_name(active_type)
              << ", active_dev=" << active_dev
              << '\n';

    const char* name = acc_get_property_string(active_dev, active_type, acc_property_name);
    const char* vendor = acc_get_property_string(active_dev, active_type, acc_property_vendor);
    const char* driver = acc_get_property_string(active_dev, active_type, acc_property_driver);
    const size_t mem_total = acc_get_property(active_dev, active_type, acc_property_memory);
    // A snapshot, not a device property: whatever other processes hold on the device
    // right now, before DES allocates anything. Not comparable across runs.
    const size_t mem_free = acc_get_property(active_dev, active_type, acc_property_free_memory);

    if (name || vendor || driver || mem_total || mem_free) {
        std::cout << "[Runtime][Device] name=" << (name ? name : "(unknown)")
                  << ", vendor=" << (vendor ? vendor : "(unknown)")
                  << ", driver=" << (driver ? driver : "(unknown)");
        char mem[32];
        if (mem_total) {
            std::snprintf(mem, sizeof(mem), "%.1f",
                          static_cast<double>(mem_total) / (1024.0 * 1024.0 * 1024.0));
            std::cout << ", mem_total_gb=" << mem;
        }
        if (mem_free) {
            std::snprintf(mem, sizeof(mem), "%.1f",
                          static_cast<double>(mem_free) / (1024.0 * 1024.0 * 1024.0));
            std::cout << ", mem_free_at_start_gb=" << mem;
        }
        std::cout << '\n';
    }

    std::cout << "[Runtime][Device] kernel=" << (using_device ? "GPU" : "CPU")
              << ", status=" << (using_device ? "gpu-offload" : "cpu-fallback") << '\n';
#endif
}

void report_mesh_info(const Variables& var, const char* tag)
{
    std::cout << "[Runtime][Mesh] " << tag
              << " nodes=" << var.nnode
              << ", elements=" << var.nelem
              << ", segments=" << var.nseg
              << '\n';
}

void report_build_snapshot()
{
    std::istringstream block(snapshot_sentinel);
    std::string line;
    while (std::getline(block, line)) {
        const std::size_t key_end = line.find(' ');
        const std::size_t sep = line.find(": ");
        const std::size_t dot = line.rfind('.', key_end);
        if (sep != std::string::npos && dot != std::string::npos) {
            const std::string topic = line.substr(dot + 1, key_end - dot - 1);
            std::cout << "[build][" << topic << "] " << line.substr(sep + 2);
            // The block cannot carry its own link time; the host line closes it,
            // so build_utc joins here exactly as it does in the .manifest.
            if (topic == "host") std::cout << " build_utc=" << exe_mtime_utc();
            std::cout << '\n';
        }
        else
            std::cout << line << '\n';
    }
#ifdef DES_HAS_CODE_DIFF
    // nvc++ discards an array nothing references, whatever __attribute__((used))
    // says, so the payload needs a volatile reference the optimizer cannot fold away.
    const char* volatile keep_code_diff = snapshot_code_diff;
    (void)keep_code_diff;
    std::cout << "[build][code-changes] embedded -- see -h for the extraction\n";
#endif
}
