#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <thread>
#include <utility>
#include <vector>

#include "runtime_info.hpp"

#ifdef ACC
#include <openacc.h>
#endif
#ifdef _OPENMP
#include <omp.h>
#endif
#ifndef WIN32
#include <pwd.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <unistd.h>
#endif
#ifdef __APPLE__
#include <cstdint>
#include <mach-o/dyld.h>
#include <mach/mach.h>
#include <sys/sysctl.h>
#include <sys/types.h>
#endif
#ifdef __linux__
#include <dirent.h>
#include <set>
#include <sys/utsname.h>
#include <utility>
#endif

#include <boost/version.hpp>
#include <nanoflann.hpp>
#ifdef HDF5
#include <H5public.h>
#endif
#ifdef USEMMG
#include <mmg/common/mmgversion.h>
#endif
#include "binaryio.hpp"
#include "constants.hpp"

namespace {

// Generated by make: the DES_* macros, and snapshot_code_diff[] under snapshot_diff=1,
// kept out of the global namespace.
#include "build_revision.hpp"

const double BYTES_PER_GIB = 1024.0 * 1024.0 * 1024.0;
const double KIB_PER_GIB = 1024.0 * 1024.0;
const char* const no_code_diff = "not embedded -- this binary was built without snapshot_diff=1";

#define DES_STR2(x) #x
#define DES_STR(x) DES_STR2(x)
// The build identity, read without running the binary: strings <exe> | grep
// '^build\.snapshot\.'. One topic per line, each carrying the prefix, so one grep prints
// the block. Versions and options only: no paths, no environment.
__attribute__((used)) const char snapshot_sentinel[] =
    "build.snapshot.code       : rev=" DES_REVISION " branch=" DES_BRANCH DES_DIRTY
    " origin=" DES_ORIGIN " state_time=" DES_STATE_TIME
    // ndims from THREED keeps build_revision.hpp dimension-neutral.
    "\nbuild.snapshot.options    :"
#ifdef THREED
    " ndims=3 "
#else
    " ndims=2 "
#endif
    DES_MAKE_OPTS
#ifdef ACC
    " gpu_cc=cc" DES_GPU_CC
#endif
    // The frame format output.cxx compiles in; layout = BINARY_FILE_REVISION.
    "\nbuild.snapshot.output     :"
#ifdef HDF5
    " container=vtkhdf"
#else
    " container=des-binary"
#endif
    " layout=" DES_STR(BINARY_FILE_REVISION)
    // version@rev: a patched submodule still reports its release's version.
    "\nbuild.snapshot.submodules :"
#ifdef ACC
    " knn-bvh=" DES_KNNBVH_REV   // no version macro, so the rev alone
#endif
    " nanoflann=" DES_STR(NANOFLANN_VERSION) "@" DES_NANOFLANN_REV   // hex 0x190 = 1.9.0
#ifdef USEMMG
    " mmg=" MMG_VERSION_RELEASE DES_MMG_REV "(" DES_SRC_MMG ")"
#endif
    // Ordered by how likely a version change explains a behaviour change.
    "\nbuild.snapshot.libs       :"
#ifdef HDF5
    " hdf5=" H5_VERSION "(" DES_SRC_HDF5 ")"
#endif
#ifdef _OPENMP
    " openmp=" DES_STR(_OPENMP) "(" DES_SRC_OPENMP ")"
#else
    " openmp=off"
#endif
#if defined(_LIBCPP_VERSION)
    " libcxx=" DES_STR(_LIBCPP_VERSION) "(toolchain)"
#elif defined(__GLIBCXX__)
    " libstdcxx=" DES_STR(__GLIBCXX__) "(toolchain)"
#endif
    " boost=" BOOST_LIB_VERSION "(" DES_SRC_BOOST ")"
    "\nbuild.snapshot.toolchain  :"
    // nvc++ and clang also define __GNUC__, so they go first. nvc++'s __VERSION__ names its
    // g++ mode and g++'s names no compiler ("8.5.0 20210514 (Red Hat 8.5.0-28)"): name both.
#if defined(__NVCOMPILER)
    " compiler=nvc++-" DES_STR(__NVCOMPILER_MAJOR__) "." DES_STR(__NVCOMPILER_MINOR__)
#elif defined(__clang__)
    " compiler=" __VERSION__
#elif defined(__GNUC__)
    " compiler=g++ " __VERSION__
#else
    " compiler=" __VERSION__
#endif
    " target="
#if defined(__aarch64__) || defined(__arm64__)
    "arm64"
#elif defined(__x86_64__)
    "x86_64"
#else
    "unknown"
#endif
#if defined(__APPLE__)
    "-darwin"
#elif defined(__linux__)
    "-linux"
#else
    "-unknown"
#endif
    // Flags by stage: compile, defines and warnings reach every .o; link reaches the
    // executable alone -- the link rule passes LDFLAGS and never CXXFLAGS.
    "\nbuild.snapshot.compile    : " DES_CXXFLAGS
    "\nbuild.snapshot.defines    :"
#ifdef THREED
    " -DTHREED"
#endif
    " " DES_DEFINES
    "\nbuild.snapshot.warnings   : " DES_WARNFLAGS
    "\nbuild.snapshot.link       : " DES_LDFLAGS
    // The build host's os is the binary's de facto glibc floor on Linux.
    "\nbuild.snapshot.host       :"
    " os=" DES_BUILD_OS
    " builder=" DES_BUILDER
    ;
#undef DES_STR
#undef DES_STR2


#ifdef ACC
acc_device_t parse_openacc_device_env(const char* env)
{
    if (!env) return acc_device_default;
    std::string s(env);
    std::transform(s.begin(), s.end(), s.begin(),
                   [](unsigned char c) { return std::tolower(c); });
    if (s == "nvidia" || s == "gpu") return acc_device_nvidia;
    if (s == "host" || s == "cpu") return acc_device_host;
    if (s == "none") return acc_device_none;
    if (s == "default") return acc_device_default;
    if (s == "not_host") return acc_device_not_host;
    return acc_device_default;
}

bool env_forces_device(const char* env, acc_device_t& device)
{
    if (!env) return false;
    device = parse_openacc_device_env(env);
    return (device != acc_device_default);
}
#endif

std::string int_or_unknown(int v)
{
    return (v >= 0) ? std::to_string(v) : std::string("unknown");
}

std::string format_double(const char* spec, double v)
{
    char buf[32];
    std::snprintf(buf, sizeof(buf), spec, v);
    return buf;
}

// %.1f in the start record and on screen; frames keep the full precision.
std::string gib_or_unknown(double gib)
{
    return (gib > 0) ? format_double("%.1f", gib) : std::string("unknown");
}

// The variable's value, or NULL when unset or empty: an empty export governs nothing.
const char* env_value(const char* name)
{
    const char* v = std::getenv(name);
    return (v && *v) ? v : NULL;
}

// The .manifest uses the input files' own layout: "[section]" then "key = value".
// A value may contain spaces (cpu_model, compiler) but never a newline.
typedef std::pair<std::string, std::string> Field;
typedef std::vector<Field> Fields;

void add(Fields& fs, const std::string& key, const std::string& value)
{
    fs.push_back(Field(key, value));
}

// A duration twice: "Nd HH:MM:SS" to read, the day part from one day up, then seconds.
void add_duration(Fields& fs, const std::string& name, double sec)
{
    const long long s = std::llround(sec);
    char buf[48];   // the longest, "106751d 23:59:59", is 16
    if (s >= 86400)
        std::snprintf(buf, sizeof(buf), "%lldd %02lld:%02lld:%02lld",
                      s / 86400, s % 86400 / 3600, s % 3600 / 60, s % 60);
    else
        std::snprintf(buf, sizeof(buf), "%02lld:%02lld:%02lld", s / 3600, s % 3600 / 60, s % 60);
    add(fs, name, buf);
    add(fs, name + "_sec", format_double("%.3f", sec));
}

// Unprobed = absent in the manifest; frames instead carry a fixed set with sentinels.
void add_section(Manifest& m, const std::string& name, const Fields& fs)
{
    if (fs.empty()) return;
    ManifestSection sec;
    sec.name = name;
    sec.fields = fs;
    m.push_back(sec);
}

void write_section(std::FILE* f, const std::string& section, const Fields& fs)
{
    std::fprintf(f, "[%s]\n", section.c_str());
    for (std::size_t i = 0; i < fs.size(); ++i)
        std::fprintf(f, "%s = %s\n", fs[i].first.c_str(), fs[i].second.c_str());
    std::fprintf(f, "\n");
}

// Provenance is diagnostic: a manifest that cannot be written warns, never aborts.
std::FILE* open_manifest(const std::string& filename, const char* mode, const char* lost)
{
    std::FILE* f = std::fopen(filename.c_str(), mode);
    if (f == NULL)
        std::cerr << "Warning: cannot open file '" << filename << "' for writing; "
                  << lost << " not recorded\n";
    return f;
}

// Check the error flag AND fclose: a record is smaller than the stdio buffer, so on a
// full disk ferror still reads clean while fclose fails and the record is lost.
void close_manifest(std::FILE* f, const std::string& filename)
{
    const bool write_failed = (std::ferror(f) != 0);
    const bool close_failed = (std::fclose(f) != 0);
    if (write_failed || close_failed)
        std::cerr << "Warning: failed writing to file '" << filename
                  << "'; run provenance may be incomplete\n";
}

// A key starts with a letter or '_', a compiler flag with '-': that tells a key=value
// payload from a bare flag list.
bool is_key_char(char c, bool first)
{
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'
        || (!first && ((c >= '0' && c <= '9') || c == '.' || c == '-'));
}

// Offset of the '=' closing a key that starts at i, or npos if none starts there.
std::size_t key_end_at(const std::string& s, std::size_t i)
{
    if (i >= s.size() || !is_key_char(s[i], true)) return std::string::npos;
    std::size_t j = i + 1;
    while (j < s.size() && is_key_char(s[j], false)) ++j;
    return (j < s.size() && s[j] == '=') ? j : std::string::npos;
}

// Splits a payload into pairs at the space that begins the NEXT key, since a value may
// hold spaces ("compiler=Apple LLVM 21.0.0 (clang-...)"). Empty for a bare flag list.
Fields parse_block_payload(const std::string& payload)
{
    Fields fs;
    std::size_t i = 0;
    while (i < payload.size()) {
        const std::size_t eq = key_end_at(payload, i);
        if (eq == std::string::npos) break;
        std::size_t end = eq + 1;
        while (end < payload.size()) {
            if (payload[end] == ' ' && key_end_at(payload, end + 1) != std::string::npos)
                break;
            ++end;
        }
        add(fs, payload.substr(i, eq - i), payload.substr(eq + 1, end - eq - 1));
        i = (end < payload.size()) ? end + 1 : end;
    }
    return fs;
}


#ifdef __APPLE__
// -1, 0 or "" for a key this hardware lacks, e.g. hw.perflevel* on Intel Macs.
int sysctl_int32(const char* name)
{
    int32_t value = 0;
    std::size_t len = sizeof(value);
    if (sysctlbyname(name, &value, &len, NULL, 0) != 0 || len != sizeof(value))
        return -1;
    return value;
}

uint64_t sysctl_uint64(const char* name)
{
    uint64_t value = 0;
    std::size_t len = sizeof(value);
    if (sysctlbyname(name, &value, &len, NULL, 0) != 0 || len != sizeof(value))
        return 0;
    return value;
}

std::string sysctl_string(const char* name)
{
    std::size_t len = 0;
    if (sysctlbyname(name, NULL, &len, NULL, 0) != 0 || len == 0)
        return std::string();
    std::string value(len, '\0');
    if (sysctlbyname(name, &value[0], &len, NULL, 0) != 0)
        return std::string();
    // len counts the trailing NUL, which does not belong in a std::string.
    value.resize(len > 0 ? len - 1 : 0);
    return value;
}
#endif // __APPLE__

#ifdef __linux__
std::string trim(const std::string& s)
{
    std::size_t b = 0, e = s.size();
    while (b < e && std::isspace(static_cast<unsigned char>(s[b]))) ++b;
    while (e > b && std::isspace(static_cast<unsigned char>(s[e-1]))) --e;
    return s.substr(b, e - b);
}

// First line of a small procfs/sysfs file, empty when unreadable.
std::string read_first_line(const char* path)
{
    std::ifstream f(path);
    if (!f) return std::string();

    std::string line;
    if (!std::getline(f, line)) return std::string();
    // /proc/device-tree properties are NUL-terminated and getline keeps the terminator.
    const std::size_t nul = line.find('\0');
    if (nul != std::string::npos) line.erase(nul);
    return trim(line);
}

// One pass over /proc/cpuinfo: model name, physical cores as distinct (package, core)
// pairs, and the ARM implementer/part ids, which are all an ARM kernel emits.
void read_proc_cpuinfo(std::string& model, int& physical_cores,
                       std::string& arm_implementer, std::string& arm_part)
{
    std::ifstream cpuinfo("/proc/cpuinfo");
    if (!cpuinfo) return;

    std::set<std::pair<int, int> > cores;
    int pkg = -1, core = -1;
    std::string line;
    while (std::getline(cpuinfo, line)) {
        const std::size_t colon = line.find(':');
        if (colon == std::string::npos) {
            // Blank line: end of one processor block.
            if (pkg >= 0 && core >= 0) cores.insert(std::make_pair(pkg, core));
            pkg = core = -1;
            continue;
        }
        const std::string key = trim(line.substr(0, colon));
        const std::string value = trim(line.substr(colon + 1));
        if (key == "model name") {
            if (model.empty()) model = value;
        }
        else if (key == "physical id") pkg = std::atoi(value.c_str());
        else if (key == "core id") core = std::atoi(value.c_str());
        else if (key == "CPU implementer") {
            if (arm_implementer.empty()) arm_implementer = value;
        }
        else if (key == "CPU part") {
            if (arm_part.empty()) arm_part = value;
        }
    }
    if (pkg >= 0 && core >= 0) cores.insert(std::make_pair(pkg, core));

    if (!cores.empty()) physical_cores = static_cast<int>(cores.size());
}

// Physical cores from sysfs, which ARM has too. cpu* is enumerated, not indexed: it is
// sparse once CPUs go offline.
int read_sysfs_physical_cores()
{
    DIR* dir = opendir("/sys/devices/system/cpu");
    if (!dir) return -1;

    const std::string root = "/sys/devices/system/cpu/";
    std::set<std::pair<int, int> > cores;
    while (const struct dirent* ent = readdir(dir)) {
        const std::string name = ent->d_name;
        if (name.compare(0, 3, "cpu") != 0 || name.size() == 3) continue;
        if (name.find_first_not_of("0123456789", 3) != std::string::npos) continue;

        const std::string topo = root + name + "/topology/";
        const std::string core = read_first_line((topo + "core_id").c_str());
        if (core.empty()) continue;
        const std::string pkg =
            read_first_line((topo + "physical_package_id").c_str());
        cores.insert(std::make_pair(pkg.empty() ? 0 : std::atoi(pkg.c_str()),
                                    std::atoi(core.c_str())));
    }
    closedir(dir);

    return cores.empty() ? -1 : static_cast<int>(cores.size());
}

// The machine from DMI, for an anonymous CPU: it still tells two hosts apart.
std::string read_dmi_model()
{
    const std::string vendor =
        read_first_line("/sys/devices/virtual/dmi/id/sys_vendor");
    const std::string product =
        read_first_line("/sys/devices/virtual/dmi/id/product_name");
    if (vendor.empty()) return product;
    if (product.empty()) return vendor;
    return vendor + " " + product;
}

// One "Key:  N kB" row of a /proc file, in GiB; 0 when absent or unreadable.
double read_proc_kb_gib(const char* path, const char* key)
{
    std::ifstream f(path);
    if (!f) return 0;

    const std::string prefix = std::string(key) + ":";
    std::string line;
    while (std::getline(f, line)) {
        if (line.compare(0, prefix.size(), prefix) == 0)
            return std::atof(trim(line.substr(prefix.size())).c_str()) / KIB_PER_GIB;
    }
    return 0;
}

// "ID-VERSION_ID" from /etc/os-release (e.g. "ubuntu-22.04"); empty when unreadable.
std::string read_os_release()
{
    std::ifstream f("/etc/os-release");
    if (!f) return std::string();

    std::string id, version, line;
    while (std::getline(f, line)) {
        // Values may be quoted; both fields are single-word by spec.
        std::string* out = NULL;
        if (line.compare(0, 3, "ID=") == 0) { out = &id; line = line.substr(3); }
        else if (line.compare(0, 11, "VERSION_ID=") == 0) { out = &version; line = line.substr(11); }
        if (!out) continue;
        line.erase(std::remove(line.begin(), line.end(), '"'), line.end());
        *out = trim(line);
    }
    if (id.empty()) return std::string();
    return version.empty() ? id : id + "-" + version;
}
#endif // __linux__

std::string read_hostname()
{
#ifndef WIN32
    char buf[256];
    if (gethostname(buf, sizeof(buf)) == 0) {
        buf[sizeof(buf)-1] = '\0';
        return std::string(buf);
    }
#endif
    return "unknown";
}

// local_now()'s format for any instant; "unknown" on failure, since strftime then
// leaves the buffer indeterminate.
std::string local_stamp(std::time_t t)
{
    char stamp[64];   // 24 fixed chars, a space, the zone: a zone over ~38 reads "unknown"
    const std::tm* local = std::localtime(&t);
    if (!local || std::strftime(stamp, sizeof(stamp), "%Y-%m-%dT%H:%M:%S%z %Z", local) == 0)
        return "unknown";
    // %z prints -0500 (GNU's %:z is not portable) or nothing; its sign follows the 19
    // chars of "YYYY-MM-DDTHH:MM:SS", and the colon goes after the hour.
    const std::size_t sign = 19;
    std::string s(stamp);
    if (s.size() > sign + 3 && (s[sign] == '+' || s[sign] == '-'))
        s.insert(sign + 3, 1, ':');
    return s;
}

// The executable's mtime: a timestamp embedded in the binary would change the binary.
std::string read_exe_mtime()
{
    char path[4096];   // Linux PATH_MAX; an over-long path degrades to "unknown"
#if defined(__APPLE__)
    uint32_t size = sizeof(path);
    if (_NSGetExecutablePath(path, &size) != 0) return "unknown";
#elif defined(__linux__)
    const ssize_t n = readlink("/proc/self/exe", path, sizeof(path) - 1);
    if (n <= 0) return "unknown";
    path[n] = '\0';
#else
    return "unknown";
#endif
#ifndef WIN32
    struct stat st;
    if (stat(path, &st) != 0) return "unknown";
    return local_stamp(st.st_mtime);
#endif
}

// The run host's OS, same labeling as the build-side DES_BUILD_OS.
std::string runtime_os()
{
#if defined(__APPLE__)
    const std::string version = sysctl_string("kern.osproductversion");
    return version.empty() ? "macos" : "macos-" + version;
#elif defined(__linux__)
    const std::string os = read_os_release();
    return os.empty() ? "linux" : os;
#else
    return "unknown";
#endif
}

// user@host, the run-side counterpart of the build's builder=.
std::string runner_id()
{
    std::string user;
#ifndef WIN32
    if (const struct passwd* pw = getpwuid(geteuid()))
        if (pw->pw_name) user = pw->pw_name;
#endif
    if (user.empty()) {
        const char* env_user = std::getenv("USER");
        user = env_user ? env_user : "unknown";
    }
    return user + "@" + read_hostname();
}


#ifdef _OPENMP
// omp_get_max_threads() is only an upper bound: with OMP_DYNAMIC on, the runtime
// may hand out fewer. Open one throwaway region to see the real team size.
int measure_omp_team_size()
{
    int team = 0;
    #pragma omp parallel default(none) shared(team)
    {
        #pragma omp single
        team = omp_get_num_threads();
    }
    return team;
}
#endif

} // namespace

bool env_sets_wait_policy()
{
    return env_value("OMP_WAIT_POLICY") || env_value("KMP_BLOCKTIME");
}

int omp_team_size_now()
{
#ifdef _OPENMP
    return measure_omp_team_size();
#else
    return -1;
#endif
}

std::string local_now()
{
    return local_stamp(std::time(NULL));
}

// Free+inactive pages on macOS (free_count includes the speculative ones), MemAvailable
// on Linux: not comparable across the two.
double host_mem_avail_gib_now()
{
#if defined(__APPLE__)
    // mach_host_self() hands out a send right we own, unlike mach_task_self().
    const mach_port_t self = mach_host_self();
    vm_size_t page = 0;
    vm_statistics64_data_t vm;
    mach_msg_type_number_t count = HOST_VM_INFO64_COUNT;
    const bool ok = host_page_size(self, &page) == KERN_SUCCESS &&
                    host_statistics64(self, HOST_VM_INFO64,
                                      reinterpret_cast<host_info64_t>(&vm),
                                      &count) == KERN_SUCCESS;
    mach_port_deallocate(mach_task_self(), self);
    if (!ok) return 0;
    return (static_cast<double>(vm.free_count) + vm.inactive_count) * page / BYTES_PER_GIB;
#elif defined(__linux__)
    return read_proc_kb_gib("/proc/meminfo", "MemAvailable");
#else
    return 0;
#endif
}

namespace {

double host_mem_rss_gib()
{
#if defined(__APPLE__)
    mach_task_basic_info info;
    mach_msg_type_number_t count = MACH_TASK_BASIC_INFO_COUNT;
    if (task_info(mach_task_self(), MACH_TASK_BASIC_INFO,
                  reinterpret_cast<task_info_t>(&info), &count) != KERN_SUCCESS)
        return 0;
    return static_cast<double>(info.resident_size) / BYTES_PER_GIB;
#elif defined(__linux__)
    return read_proc_kb_gib("/proc/self/status", "VmRSS");
#else
    return 0;
#endif
}

// Bytes on macOS, kB on Linux, where the kernel also refreshes it lazily.
double ru_maxrss_gib()
{
#ifndef WIN32
    struct rusage ru;
    if (getrusage(RUSAGE_SELF, &ru) != 0) return 0;
#if defined(__APPLE__)
    return static_cast<double>(ru.ru_maxrss) / BYTES_PER_GIB;
#else
    return static_cast<double>(ru.ru_maxrss) / KIB_PER_GIB;
#endif
#else
    return 0;
#endif
}

} // namespace

double sample_rss_gib(double& peak_rss_gib)
{
    const double rss_gib = host_mem_rss_gib();
    peak_rss_gib = std::max(peak_rss_gib, std::max(ru_maxrss_gib(), rss_gib));
    return rss_gib;
}

double process_cpu_time_sec()
{
#ifndef WIN32
    struct rusage ru;
    if (getrusage(RUSAGE_SELF, &ru) != 0) return 0;
    return ru.ru_utime.tv_sec + ru.ru_utime.tv_usec * 1e-6
         + ru.ru_stime.tv_sec + ru.ru_stime.tv_usec * 1e-6;
#else
    return 0;
#endif
}

double host_load_avg_1m()
{
#ifndef WIN32
    double la[1] = {0};
    if (getloadavg(la, 1) != 1) return 0;
    return la[0];
#else
    return 0;
#endif
}

double device_mem_used_dev_gib(const DeviceInfo& dev)
{
#ifdef ACC
    if (dev.using_gpu && dev.mem_total_gib > 0) {
        const acc_device_t type = acc_get_device_type();
        const size_t free_now =
            acc_get_property(acc_get_device_num(type), type, acc_property_free_memory);
        if (free_now)
            return dev.mem_total_gib - static_cast<double>(free_now) / BYTES_PER_GIB;
    }
#else
    (void)dev;
#endif
    return 0;
}

BuildInfo probe_build_info()
{
    BuildInfo b;
    b.rev = DES_REVISION;
    b.branch = DES_BRANCH;
    const std::string dirty(DES_DIRTY);   // " dirty=2f/+13/-12"/" dirty=unknown", "" = clean
    const std::size_t eq = dirty.find('=');
    b.dirty = (eq == std::string::npos) ? "clean" : dirty.substr(eq + 1);
    b.origin = DES_ORIGIN;
    b.state_time = DES_STATE_TIME;
    b.build_os = DES_BUILD_OS;
    b.builder = DES_BUILDER;
    b.exe_mtime = read_exe_mtime();

    return b;
}


CpuInfo probe_cpu_info(bool wait_policy_from_des)
{
    CpuInfo cpu;
    cpu.model = "unknown";
    cpu.logical_cores = -1;
    cpu.physical_cores = -1;
    cpu.perf_cores = -1;
    cpu.eff_cores = -1;
    cpu.mem_total_gib = 0;
    cpu.mem_avail_gib = 0;
    cpu.openmp_enabled = false;
    cpu.omp_team_size = -1;
    cpu.omp_max_threads = -1;
    cpu.omp_num_procs = -1;
    cpu.omp_dynamic = false;

    cpu.os = runtime_os();
    cpu.runner = runner_id();
    cpu.mem_avail_gib = host_mem_avail_gib_now();

    const unsigned int hw_threads = std::thread::hardware_concurrency();
    if (hw_threads) cpu.logical_cores = static_cast<int>(hw_threads);

#ifdef __APPLE__
    const std::string brand = sysctl_string("machdep.cpu.brand_string");
    if (!brand.empty()) cpu.model = brand;
    else {
        const std::string hw_model = sysctl_string("hw.model");
        if (!hw_model.empty()) cpu.model = hw_model;
    }
    cpu.physical_cores = sysctl_int32("hw.physicalcpu");
    const int logical = sysctl_int32("hw.logicalcpu");
    if (logical > 0) cpu.logical_cores = logical;
    // Only a two-tier part maps onto perf/eff; with a third tier, eff stays unknown.
    cpu.perf_cores = sysctl_int32("hw.perflevel0.physicalcpu");
    if (sysctl_int32("hw.nperflevels") == 2)
        cpu.eff_cores = sysctl_int32("hw.perflevel1.physicalcpu");
    const uint64_t memsize = sysctl_uint64("hw.memsize");
    if (memsize) cpu.mem_total_gib = static_cast<double>(memsize) / BYTES_PER_GIB;
#elif defined(__linux__)
    // /proc/cpuinfo first, then sysfs.
    std::string model, arm_implementer, arm_part;
    read_proc_cpuinfo(model, cpu.physical_cores, arm_implementer, arm_part);
    if (cpu.physical_cores < 0) cpu.physical_cores = read_sysfs_physical_cores();

    // The chip, else the machine: device-tree on ARM boards, DMI on servers.
    if (model.empty()) model = read_first_line("/proc/device-tree/model");
    if (model.empty()) model = read_dmi_model();
    if (model.empty() && !arm_implementer.empty() && !arm_part.empty()) {
        // An anonymous ARM core by its raw ids: a part-number table would go stale.
        struct utsname uts;
        const std::string machine = (uname(&uts) == 0) ? uts.machine : "";
        model = machine + (machine.empty() ? "" : " ") +
                "(CPU implementer " + arm_implementer +
                ", part " + arm_part + ")";
    }
    if (!model.empty()) cpu.model = model;
    cpu.mem_total_gib = read_proc_kb_gib("/proc/meminfo", "MemTotal");
#endif

#ifdef _OPENMP
    cpu.openmp_enabled = true;
    cpu.omp_max_threads = omp_get_max_threads();
    cpu.omp_num_procs = omp_get_num_procs();
    cpu.omp_dynamic = (omp_get_dynamic() != 0);
    cpu.omp_team_size = measure_omp_team_size();
#endif

    cpu.wait_policy_src = wait_policy_from_des ? "des-default"
                        : env_sets_wait_policy() ? "env" : "runtime";

    return cpu;
}

Manifest compose_manifest(const Param& param, const BuildInfo& build,
                          const CpuInfo& cpu, const DeviceInfo& dev)
{
    Manifest m;
    Fields run;
    add(run, "modelname", param.sim.modelname);
    add(run, "restarting", param.sim.is_restarting ? "yes" : "no");
    if (param.sim.is_restarting) {
        add(run, "restart_from_model", param.sim.restarting_from_modelname);
        add(run, "restart_from_frame", std::to_string(param.sim.restarting_from_frame));
    }
    add(run, "start_time", local_now());
    add_section(m, "runtime.model", run);

    Fields host;
    add(host, "os", cpu.os);
    add(host, "runner", cpu.runner);
    add(host, "cpu_model", cpu.model);
    add(host, "physical_cores", int_or_unknown(cpu.physical_cores));
    add(host, "logical_cores", int_or_unknown(cpu.logical_cores));
    add(host, "perf_cores", int_or_unknown(cpu.perf_cores));
    add(host, "eff_cores", int_or_unknown(cpu.eff_cores));
    add(host, "mem_total_gib", gib_or_unknown(cpu.mem_total_gib));
    add(host, "mem_avail_at_start_gib", gib_or_unknown(cpu.mem_avail_gib));
    add_section(m, "runtime.host", host);

    Fields device;
    add(device, "kernel", dev.kernel);
    // Outside the using_gpu block: "none" is why a run found no device.
    if (dev.acc_build)
        add(device, "visible_devices", dev.visible_devices);
    if (dev.using_gpu) {
        if (!dev.name.empty()) add(device, "name", dev.name);
        add(device, "selected", std::to_string(dev.active_dev) + "/"
                              + std::to_string(dev.num_devices));
        if (!dev.cuda_driver.empty()) add(device, "cuda_driver", dev.cuda_driver);
        add(device, "mem_total_gib", gib_or_unknown(dev.mem_total_gib));
        add(device, "mem_free_at_start_gib", gib_or_unknown(dev.mem_free_gib));
    }
    add_section(m, "runtime.device", device);

    Fields threads;
    add(threads, "openmp", cpu.openmp_enabled ? "enabled" : "disabled");
    if (cpu.openmp_enabled) {
        add(threads, "omp_threads", int_or_unknown(cpu.omp_team_size));
        add(threads, "omp_max_threads", int_or_unknown(cpu.omp_max_threads));
        add(threads, "omp_num_procs", int_or_unknown(cpu.omp_num_procs));
        add(threads, "omp_dynamic", cpu.omp_dynamic ? "on" : "off");
        // What was set, not one resolved policy: runtimes differ in which of the two they
        // honour. Always written, since absent would read as not probed.
        std::string policy;
        if (const char* wait = env_value("OMP_WAIT_POLICY"))
            policy = wait;
        if (const char* bt = env_value("KMP_BLOCKTIME"))
            policy += (policy.empty() ? "" : "+") + std::string("blocktime=") + bt;
        add(threads, "omp_wait_policy_eff", policy.empty() ? "default" : policy);
        add(threads, "omp_wait_policy_src", cpu.wait_policy_src);
    }
    add_section(m, "runtime.threads", threads);

    // Only the variables that are set, OMP_WAIT_POLICY included where main() set it.
    const char* const env_names[] = {
        "OMP_NUM_THREADS", "OMP_THREAD_LIMIT", "OMP_DYNAMIC", "OMP_PROC_BIND",
        "OMP_PLACES", "OMP_WAIT_POLICY", "KMP_BLOCKTIME",
    };
    // Device selection, on an ACC build only: elsewhere these steer nothing.
    const char* const acc_env_names[] = {
        "CUDA_VISIBLE_DEVICES", "ACC_DEVICE_TYPE", "ACC_DEVICE_NUM",
        "NVCOMPILER_ACC_DEVICE_TYPE", "NVCOMPILER_ACC_DEVICE_NUM"
    };
    Fields env;
    for (std::size_t i = 0; i < sizeof(env_names) / sizeof(env_names[0]); ++i)
        if (const char* v = std::getenv(env_names[i]))
            add(env, env_names[i], v);
    if (dev.acc_build)
        for (std::size_t i = 0; i < sizeof(acc_env_names) / sizeof(acc_env_names[0]); ++i)
            if (const char* v = std::getenv(acc_env_names[i]))
                add(env, acc_env_names[i], v);
    add_section(m, "runtime.env", env);

    // The embedded block as [build.*] sections; exe_mtime joins the host line, the block's
    // last, so the parse files it there.
    const std::string block = std::string(snapshot_sentinel)
                            + " exe_mtime=" + build.exe_mtime;
    std::istringstream blocklines(block);
    std::string line;
    Fields compile, link, other;        // the bare-flag-list topics, by stage
    while (std::getline(blocklines, line)) {
        const std::size_t sep = line.find(" : ");
        if (sep == std::string::npos) {
            // Unreachable today, but the payloads are preprocessor-assembled: keep, not lose.
            add(other, "unparsed", line);
            continue;
        }
        std::string topic = line.substr(0, sep);
        const std::size_t dot = topic.rfind('.');
        if (dot != std::string::npos) topic = topic.substr(dot + 1);
        while (!topic.empty() && topic[topic.size() - 1] == ' ')   // column padding
            topic.erase(topic.size() - 1);

        const std::string payload = line.substr(sep + 3);
        const Fields fields = parse_block_payload(payload);
        if (fields.empty()) {
            if (topic == "link")         add(link, "flags", payload);
            else if (topic == "compile") add(compile, "flags", payload);
            else                         add(compile, topic, payload);
        }
        else
            add_section(m, "build." + topic, fields);
    }
    add_section(m, "build.compile", compile);
    add_section(m, "build.link", link);
    add_section(m, "build.unparsed", other);
    return m;
}

// The start record: its sections, then the code-changes block or the line saying none.
static void write_record(std::FILE* f, const Manifest& manifest)
{
    for (std::size_t i = 0; i < manifest.size(); ++i)
        write_section(f, manifest[i].name, manifest[i].fields);

#ifdef DES_HAS_CODE_DIFF
    // Verbatim, so the binary's sed recipe reads it here too; last, as the one non-INI and
    // unbounded (1 MB) part.
    std::fprintf(f, "%s\n", snapshot_code_diff);
#else
    // Said, not left out: "not built with it" must not read like a clean tree. A comment,
    // so no INI reader takes it for a key.
    std::fprintf(f, "# build.code-changes: %s\n", no_code_diff);
#endif
}

void write_manifest(const Param& param, const Manifest& manifest, bool keep_existing)
{
    const std::string filename(param.sim.modelname + ".manifest");

    // A fresh run truncates, like .info; a restart, or a run about to fail, appends: it
    // replaces no frames, so it must not replace their record.
    const bool append = param.sim.is_restarting || keep_existing;
    std::FILE* f = open_manifest(filename, append ? "a" : "w", "run provenance");
    if (f == NULL) return;

    // A seam between records, but none before the first (a restart into a new directory).
    std::fseek(f, 0, SEEK_END);
    if (append && std::ftell(f) > 0)
        std::fprintf(f, keep_existing
                        ? "# ---- a run that could not start follows ----\n\n"
                        : "# ---- restart: another record follows ----\n\n");

    write_record(f, manifest);

    close_manifest(f, filename);
}

void write_manifest_end(const Param& param, const Manifest& manifest, const Variables& var,
                        int steps_this_run, int64_t wall_ns, int64_t init_ns,
                        int64_t compute_ns, double peak_rss_gib)
{
    // What a reader asks first leads: did it finish and why, how long, how far, what it
    // cost; then where the time went, each phase as time, count and average.
    Fields end;
    add(end, "end_time", local_now());
    // Which of the time loop's two exits fired; max_steps when both did.
    add(end, "stopped_by", var.steps >= param.sim.max_steps ? "max_steps" : "max_time_in_yr");
    add_duration(end, "wall_time", wall_ns * 1e-9);
    add(end, "last_step", std::to_string(var.steps));
    // Below last_step only on a restart, which resumes the step count.
    add(end, "steps_this_run", std::to_string(steps_this_run));
    add(end, "model_time_yr", format_double("%.6g", var.time / YEAR2SEC));
    add(end, "nnode", std::to_string(var.nnode));
    add(end, "nelem", std::to_string(var.nelem));
    // Against wall_time x omp_threads, the run's parallel efficiency.
    const double cpu_sec = process_cpu_time_sec();
    if (cpu_sec > 0) add_duration(end, "cpu_time", cpu_sec);
    // %.3g, not gib_or_unknown's %.1f: a small run's peak would read 0.0.
    if (peak_rss_gib > 0) add(end, "mem_peak_rss_gib", format_double("%.3g", peak_rss_gib));

    // The screen's time summary: wall = init + compute + remesh + output, compute being the
    // remainder. Per step divides by this run's steps, not the resumed count the screen uses.
    add_duration(end, "init_time", init_ns * 1e-9);
    add_duration(end, "compute_time", compute_ns * 1e-9);
    add(end, "compute_sec_per_step", format_double("%.6g", compute_ns * 1e-9 / steps_this_run));
    add_duration(end, "remesh_time", var.func_time.remesh_time * 1e-9);
    add(end, "remeshings", std::to_string(var.nremesh));
    // Absent without a remesh, as on screen; outputs >= 1 (the frame before the loop).
    if (var.nremesh > 0)
        add(end, "remesh_sec_per_remesh",
            format_double("%.6g", var.func_time.remesh_time * 1e-9 / var.nremesh));
    add_duration(end, "output_time", var.func_time.output_time * 1e-9);
    add(end, "outputs", std::to_string(var.noutput));
    add(end, "output_sec_per_output",
        format_double("%.6g", var.func_time.output_time * 1e-9 / var.noutput));

    // Appended to this run's record: after its start sections, before any restart's seam.
    const std::string filename(param.sim.modelname + ".manifest");
    std::FILE* f = open_manifest(filename, "a", "run end");
    if (f == NULL) return;
    // The start record exists only in this file: one deleted or emptied during the run
    // gets it back from memory, so the end never stands alone.
    std::fseek(f, 0, SEEK_END);
    if (std::ftell(f) == 0) {
        std::fprintf(f, "# ---- the manifest went missing during the run: record rewritten"
                        " at its end ----\n\n");
        write_record(f, manifest);
    }
    std::fprintf(f, "\n");
    write_section(f, "runtime.end", end);
    close_manifest(f, filename);
}

DeviceInfo init_offload_device()
{
    DeviceInfo dev;
    dev.acc_build = false;
    dev.using_gpu = false;
    dev.kernel = "CPU";
    dev.num_devices = 0;
    dev.active_dev = -1;
    dev.mem_total_gib = 0;
    dev.mem_free_gib = 0;

#ifdef ACC
    dev.acc_build = true;

    const char* visible = std::getenv("CUDA_VISIBLE_DEVICES");
    dev.visible_devices = !visible ? "all" : (*visible ? visible : "none");

    const int n_nvidia = acc_get_num_devices(acc_device_nvidia);
    dev.num_devices = n_nvidia;

    acc_device_t forced = acc_device_default;
    const bool forced_by_env =
        env_forces_device(std::getenv("ACC_DEVICE_TYPE"), forced) ||
        env_forces_device(std::getenv("NVCOMPILER_ACC_DEVICE_TYPE"), forced);

    if (forced_by_env) {
        acc_set_device_type(forced);
        acc_init(forced);
    }
    else if (n_nvidia > 0) {
        acc_set_device_type(acc_device_nvidia);
        acc_init(acc_device_nvidia);
    }
    else {
        acc_set_device_type(acc_device_host);
        acc_init(acc_device_host);
    }

    const acc_device_t active_type = acc_get_device_type();
    const int active_dev = acc_get_device_num(active_type);
    dev.using_gpu = (active_type == acc_device_nvidia && n_nvidia > 0);
    dev.kernel = dev.using_gpu ? "GPU" : "CPU";
    dev.active_dev = dev.using_gpu ? active_dev : -1;

    const char* name = acc_get_property_string(active_dev, active_type, acc_property_name);
    const char* driver = acc_get_property_string(active_dev, active_type, acc_property_driver);
    if (name) dev.name = name;
    if (driver) dev.cuda_driver = driver;

    const size_t mem_total = acc_get_property(active_dev, active_type, acc_property_memory);
    if (mem_total)
        dev.mem_total_gib = static_cast<double>(mem_total) / BYTES_PER_GIB;
    const size_t mem_free = acc_get_property(active_dev, active_type, acc_property_free_memory);
    if (mem_free)
        dev.mem_free_gib = static_cast<double>(mem_free) / BYTES_PER_GIB;
#endif

    return dev;
}

// "[group][topic] key=value, ..." for the section "group.topic".
static void print_section(const ManifestSection& sec)
{
    const std::size_t dot = sec.name.find('.');
    std::cout << '[' << sec.name.substr(0, dot) << ']'
              << '[' << (dot == std::string::npos ? "" : sec.name.substr(dot + 1)) << ']';
    for (std::size_t k = 0; k < sec.fields.size(); ++k)
        std::cout << (k ? ", " : " ") << sec.fields[k].first << '=' << sec.fields[k].second;
    std::cout << '\n';
}

void report_build_and_runtime_info(const Manifest& manifest)
{
    const std::string groups[] = { "build.", "runtime." };
    for (std::size_t g = 0; g < 2; ++g) {
        for (std::size_t i = 0; i < manifest.size(); ++i)
            if (manifest[i].name.compare(0, groups[g].size(), groups[g]) == 0)
                print_section(manifest[i]);
        if (g == 0) {
#ifdef DES_HAS_CODE_DIFF
            std::cout << "[build][code-changes] embedded -- see -h for the extraction\n";
#else
            std::cout << "[build][code-changes] " << no_code_diff << '\n';
#endif
        }
    }
}

void report_mesh_info(const Variables& var, const char* tag)
{
    std::cout << "[Runtime][Mesh] " << tag
              << " nodes=" << var.nnode
              << ", elements=" << var.nelem
              << ", segments=" << var.nseg
              << '\n';
}
