name: Test escarpment retreat

domain:
    npdata: ['./gospl_mesh','v','c','z']
    flowdir: 1
    seadepo: False
    bc: '1000'

time:
    start: 0.
    end: 50.e6
    tout: 5000.0
    dt: 1.0

spl:
    K: 4.e-7
    d: 0.
    m: 0.4

diffusion:
    hillslopeKa: 0.02
    hillslopeKm: 0.1

sea:
    position: -10.

climate:
  - start: 0.
    uniform: 1

output:
    dir: 'coupling_slow'
