#!/usr/bin/env python3
"""Emit per-object dependencies on per-feature build stamps.

Lets the Makefile rebuild only the objects a feature macro can actually reach
instead of all of them. DERIVED, never hand-maintained: a hand-written map is
wrong the moment an #ifdef moves into a widely included header, and it fails
silently -- a stale object links into a binary that runs. Reachability is
therefore transitive over local #include edges, and a macro reaching everything
is reported as universal so the Makefile can leave it in the global stamp.

    gen_feature_deps.py --obj-suffix .2d.o --stamp-prefix .build-flags- \
        --sources a.cxx b.cxx --headers x.hpp y.hpp -- HDF5 USEMMG

Writes makefile syntax to stdout.
"""

import argparse
import os
import re
import sys

# Local includes only: no feature macro of ours lives in a system header.
INCLUDE_RE = re.compile(r'^[ \t]*#[ \t]*include[ \t]*"([^"]+)"', re.M)


def macro_re(macro):
    """Any #if/#ifdef/#ifndef/#elif naming the macro. Anchored on the directive
    so a mention in a comment or string does not widen the set."""
    return re.compile(r'^[ \t]*#[ \t]*(?:if|ifdef|ifndef|elif)\b[^\n]*\b%s\b'
                      % re.escape(macro), re.M)


def read(path):
    try:
        with open(path, 'r', errors='ignore') as f:
            return f.read()
    except OSError:
        return ''


def transitive_headers(source, header_index, cache):
    """Every local header reachable from source, following includes recursively."""
    if source in cache:
        return cache[source]
    cache[source] = set()          # first: absorbs include cycles
    seen = set()
    stack = [source]
    while stack:
        text = read(stack.pop())
        for inc in INCLUDE_RE.findall(text):
            base = os.path.basename(inc)
            path = header_index.get(base)
            if path is not None and base not in seen:
                seen.add(base)
                stack.append(path)
    cache[source] = seen
    return seen


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--obj-suffix', required=True,
                    help='replaces .cxx in an object name, e.g. .2d.metal.o')
    ap.add_argument('--stamp-prefix', required=True,
                    help='per-feature stamp path prefix, e.g. .build-flags-')
    ap.add_argument('--stamp-suffix', default='',
                    help='per-feature stamp path suffix, e.g. .2d')
    ap.add_argument('--sources', nargs='*', default=[])
    ap.add_argument('--headers', nargs='*', default=[])
    ap.add_argument('macros', nargs='*')
    args = ap.parse_args()

    sources = [s for s in args.sources if s.endswith('.cxx')]
    if not sources:
        sys.exit('gen_feature_deps: no .cxx sources given')

    # By basename: an #include may carry a path prefix the Makefile omits.
    header_index = {}
    for h in args.headers:
        header_index.setdefault(os.path.basename(h), h)

    cache = {}
    print('# Generated by utils/gen_feature_deps.py -- do not edit.')
    print('# Which objects each feature macro can reach, transitively through '
          'local headers.')

    for macro in args.macros:
        pattern = macro_re(macro)
        hits = []
        for src in sources:
            reached = pattern.search(read(src)) is not None
            if not reached:
                for base in transitive_headers(src, header_index, cache):
                    if pattern.search(read(header_index[base])):
                        reached = True
                        break
            if reached:
                hits.append(src)

        stamp = '%s%s%s' % (args.stamp_prefix, macro, args.stamp_suffix)
        if not hits:
            print('# %s: reaches no object' % macro)
            continue
        if len(hits) == len(sources):
            print('# %s: universal (%d/%d objects)' % (macro, len(hits),
                                                       len(sources)))
        else:
            print('# %s: %d/%d objects' % (macro, len(hits), len(sources)))
        objs = ' '.join(s[:-len('.cxx')] + args.obj_suffix for s in hits)
        print('%s: %s' % (objs, stamp))
        # As a variable too, so the stamp recipe can DELETE these rather than
        # trust mtime ordering -- make 3.81 compares to the whole second.
        print('FEATURE_%s_OBJS = %s' % (macro, objs))


if __name__ == '__main__':
    main()
