title: DynEarthSol
url: "https://geoflac.github.io"
baseurl: "/DynEarthSol"
logo: "/assets/images/favicon.png"
description: "Dynamic Earth Solver, a standard finite element transplant of geoflac for unstructured meshes with P1 elements in 2D and 3D."
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-include-cache
collections:
  pages:
    output: true
    permalink: /:name/
