name: Basic build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'
      - '.zenodo.json'
      - 'CITATION.cff'
      - '*.md'
      - '*.py'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'
      - '.zenodo.json'
      - 'CITATION.cff'
      - '*.md'
      - '*.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: get boost and hdf5
      run: |
        echo Install boost-program-options and hdf5 ====================
        sudo apt-get update
        sudo apt-get install -y libboost-program-options-dev libhdf5-serial-dev make pkg-config
    - name: make debug 2d
      run: make clean ndims=2; make ndims=2 opt=0 openmp=0 hdf5=0
    - name: make debug 3d
      run: make clean ndims=3; make ndims=3 opt=0 openmp=0 hdf5=0
    - name: make 2d
      run: make clean ndims=2; make ndims=2 opt=2 openmp=1 hdf5=0
    - name: make 3d
      run: make clean ndims=3; make ndims=3 opt=2 openmp=1 hdf5=0
    - name: make 3d hdf5
      # No HDF5_*_DIR: the Makefile finds the paths itself.
      run: make clean ndims=3; make ndims=3 opt=2 openmp=1 hdf5=1
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
