name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: configure
    #   run: ./configure
    - name: make
      run:  |
        echo Install boost-program-options ====================
        sudo apt install libboost-program-options-dev
        make
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
