name: C/C++ CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'
      - '.zenodo.json'
      - 'CITATION.cff'
      - '*.md'
      - '*.py'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'
      - '.zenodo.json'
      - 'CITATION.cff'
      - '*.md'
      - '*.py'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: get g++ version
      run: g++ --version
