name: nvc build

on:
  push:
    branches: [ "master", "*gpu*" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/nvhpc:25.7-devel-cuda_multi-ubuntu22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y libboost-program-options-dev libhdf5-serial-dev make pkg-config

    - name: Fix git safe directory
      run: git config --global --add safe.directory '*'

    - name: Build all targets (CPU & GPU)
      run: |
        NVARCH=$(uname -s)_$(uname -m)
        export NVHPC_DIR=/opt/nvidia/hpc_sdk/${NVARCH}/25.7
        export HDF5_INCLUDE_DIR=$(pkg-config --cflags-only-I hdf5-serial | sed 's/-I//g' | tr -d ' ')
        export HDF5_LIB_DIR=$(pkg-config --libs-only-L hdf5-serial | sed 's/-L//g' | tr -d ' ')

        BASE_MAKE="make hdf5=1 NVHPC_DIR=$NVHPC_DIR HDF5_LIB_DIR=$HDF5_LIB_DIR HDF5_INCLUDE_DIR=$HDF5_INCLUDE_DIR"

        # make cleanall && $BASE_MAKE ndims=2 nprof=1 opt=0
        # make cleanall && $BASE_MAKE ndims=3 nprof=1 opt=0
        make cleanall && $BASE_MAKE ndims=2 openacc=1 -j SM=80
        make cleanall && $BASE_MAKE ndims=3 openacc=1 -j SM=80
        make cleanall && $BASE_MAKE ndims=2 openacc=1 nprof=1 -j SM=80
        make cleanall && $BASE_MAKE ndims=3 openacc=1 nprof=1 -j SM=80